### ISSUE TITLE
Refactor errors

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-server#1034]
We don't have standard way to define errors in code and cause following problems:

- Some of the api return incorrect status code
- Exposing unexpected detail of error in api response, e.g. For production environment, should not show sql error in response. We should log the details and response should only show unexpected error.

Discussions:

- Which layer should be responsible to the status code (error name), store, provider or handler?
- Should we wrap the errors so that we can trace how the error occur? How to wrap? And how to generate the error message for response, should not show the whole trace?

Confirmed todos:

- Remove error code, should use error name instead

**Comment by louischan-oursky** [comment]
- [ ] Very detailed validation error
- [ ] Refactor APIHandler lifecycle (https://github.com/SkygearIO/skygear-server/issues/1031)
- [ ] Convert all endpoints to use JSON schema
- [ ] Replace InvalidArgument with ValidationError
- [ ] Review if we can remove other 4xx error names
- [ ] Add missing provider layer (authInfo and userprofile)
- [ ] Status code is determined by the error name
- [ ] Provider is responsible for generating error. It inspects error generated by store.
