### ISSUE TITLE
Handle pubsub messages in multi instance scenario

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#105]
To fix #91, we have to handle how pubsub messages are routed to the client. To solve this, the leader instance will be asked to keep pubsub connections for all clients. Pubsub generated from other instances should forward pubsub messages to the leader instance.

Tasks:

* add new configuration envvar for specifying the leader pubsub URL
* forward pubsub messages generated from the instance to the leader (which includes subscriptions and cloudcode-generated messages)
* leader should be aware that the messages coming from the non-leaders are generated server side and not generated client side

**Comment by rickmak** [comment]
Revisiting this issue, in https://github.com/SkygearIO/skygear-server/pull/127 we added the configuration on slave and disabled the whole pubsub and cron feature at slave mode.

So the do @cheungpat think following two feature are still meaningful to implement
> 
- forward pubsub messages generated from the instance to the leader (which includes subscriptions and cloudcode-generated messages)
- leader should be aware that the messages coming from the non-leaders are generated server side and not generated client side

Or better tol provide a deployment example on how to route the traffic correctly using the program like nginx?

**Comment by cheungpat** [comment]
@rickmak Thanks for bringing it to my attention.

I think the feature is complete in skygear-server and py-skygear to support multiple instances. Agree that we should have deployment example. Where to put it?

> forward pubsub messages generated from the instance to the leader (which includes subscriptions and cloudcode-generated messages)

Cloudcode generated messages are forwarded to leader using PUBSUB_URL. In slave mode, skygear-server does not generate notifications for subscriptions

> leader should be aware that the messages coming from the non-leaders are generated server side and not generated client side

This is just a reminder not to cause infinite loop forwarding notifications among multiple instances. Since only the leader will act as pubsub hub. This is a non-issue.

**Comment by rickmak** [comment]
Let put the example here: https://github.com/skygear-demo/multiple-server
