### ISSUE TITLE
Can the Gateway participate in the refresh token flow?

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1078]
I mean if the client uses an expired access token to call microservice, can the Gateway participate in the refresh token flow and let the client SDK to perform the flow?

@kiootic

**Comment by kiootic** [comment]
Seems the gateway will:
https://github.com/SkygearIO/skygear-server/blob/4e37193c62a0021d6c53d6dca2ee6784e2da7fb0/pkg/gateway/middleware/authinfo.go#L50-L62

**Comment by louischan-oursky** [comment]
Thank you Terry!
