### ISSUE TITLE
Build asset gear in CI pipeline

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-server#1086]
CI pipeline attempts to build and push docker image to image registry. However, asset gear is not built and CI deployment would fail.

ref:
https://github.com/SkygearIO/skygear-server/blob/a3e5b0daf9cfeff30f03d08cf8037862732d1816/Makefile#L115

**Comment by louischan-oursky** [comment]
Fixed in 87bceaa406e94c7b7cba39f58a81ce312cf0ae97
