### ISSUE TITLE
Update constraint on app name

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-server#1118]
Update current constraint on app name (`^[a-zA-Z][a-zA-Z0-9]{0,11}$`). It should be a valid k8s namespace and not a reserved name.

- [ ] AppName to be a valid DNS label and k8s name no longer than 36 bytes
- [ ] Introduce AppName blacklist with external list (`kube-system`, `skygear`, `default`, etc)
- [ ] ServiceName to be a valid DNS label and k8s name no longer than 36 bytes

**Comment by kiootic** [comment]
@louischan-oursky where do you get the limit of 36 bytes? [Source code](https://godoc.org/k8s.io/apimachinery/pkg/api/validation#ValidateNamespaceName) seems to indicate same limit as DNS label (i.e. 63 bytes).

**Comment by louischan-oursky** [comment]
36 bytes is the current length we are using (the length of a canonical UUID4). I think 63 bytes is also OK.
