### ISSUE TITLE
APIs to return template information

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-server#1123]
Gears should have APIs to return supported template types and default template. The APIs should have no access control, and return static content (i.e. independent of tenant config).

**Comment by kiootic** [comment]
Some thoughts and notes:

Currently the gears are mounted at path `/_{id}` at the gateway. e.g. `https://example.com/_auth` for auth gear. This is a convention among the between Skygear components.

Apart from this convention, do we want to have other conventions, so that we can have 'dynamic discovery' of Skygear app's configuration? For example:
- obtaining the list of gears enabled for an app
- checking whether MFA is required for an app
- the focus of this issue, getting a list of templates required by a gear

There's some considerations:
- Do we want to support potentially out-of-tree gears? (i.e. gears not maintained in this repo) Currently we have RBAC service (a potential gear), which is hosted at other repo. If we want to support them, we'll need to define common gear APIs, so that gateway could interact with it.
- Do we want a cleaner and stricter responsibility separation between components? Currently the tenant config definition is shared across components. For example, if we add a field in some gear's configuration, we'll need to deploy every components, including the control-plane. We have `nextimportslint` to enforce isolation between gears in this repo, but it seems we're circumventing it by pushing codes into core.

**Comment by chpapa** [comment]
>     * Do we want to support potentially out-of-tree gears? (i.e. gears not maintained in this repo) Currently we have RBAC service (a potential gear), which is hosted at other repo. If we want to support them, we'll need to define common gear APIs, so that gateway could interact with it.

This has always been the plan, and there was discussion in early dates of Skygear 2.0 revamp planning, that we should keep the shared interfaces for gears minimal.
