### ISSUE TITLE
Customize CORS header handling at gateway

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-server#1135]
Currently, the gateway would eat all CORS header from upstream (gears, microservices, etc.), and replace them as specified in tenant config. In some situations, this may not be desirable. For example, we'd like to pass through CORS header from asset gears. We'll need some mechanism to customize CORS header handling at gateway.

**Comment by louischan-oursky** [comment]
Asset Gear: Upstream headers overwrite standalone mode headers
Gateway: Gateway respect upstream CORS headers.
