### ISSUE TITLE
Include informational error message for misconfigured VALID_HOSTS

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1139]
We have some places directly writing plain text. If the client is blindly decoding JSON, they will fail without knowing why.

---

Conclusion:

As shown in the title.

**Comment by louischan-oursky** [comment]
```
$ rg 'http.Error'
pkg/gateway/middleware/deployment_route.go
27:                     http.Error(w, "Fail to match deployment route", http.StatusNotFound)

pkg/gateway/middleware/tenant.go
32:                     http.Error(w, fmt.Sprintf("%s is not support in current app plan", gear), http.StatusForbidden)
38:                     http.Error(w, err.Error(), http.StatusBadRequest)
43:                     http.Error(w, fmt.Sprintf("%s gear %s environment is not supported", gear, gearVersion), http.StatusVariantAlsoNegotiates)

pkg/gateway/middleware/app.go
33:                     http.Error(w, "App not found", http.StatusBadRequest)
40:                     http.Error(w, "Deployment not found", http.StatusInternalServerError)
58:                     http.Error(w, "Fail to get deployment hooks", http.StatusInternalServerError)

migrate/cmd/migrate/main.go
116:                            http.Error(w, "Please send a request body", 400)

pkg/auth/handler/sso/auth_handler.go
150:            http.Error(w, "Unknown provider", http.StatusBadRequest)
156:            http.Error(w, "Failed to decode request", http.StatusBadRequest)
161:            http.Error(w, "Failed to validate request", http.StatusBadRequest)
169:            http.Error(w, "Failed to decode state", http.StatusBadRequest)
178:            http.Error(w, "Invalid callback URL", http.StatusBadRequest)
192:                    http.Error(w, "Invalid UXMode", http.StatusBadRequest)
```

I had a short discussion with @carmenlau and she told me her concern that the client may not expecting a JSON response. Any thoughts? @kiootic

**Comment by kiootic** [comment]
> the client may not expecting a JSON response.

I agree, the client may expect JSON, XML, protobuf, etc.

I'll suggest just keep it as-is at gateway, since there's not much we can do here (e.g. nginx returns a generic 404 page too). For auth gear (i.e. SSO auth handler), it is a user facing endpoint so we should return a user readable message.

**Comment by louischan-oursky** [comment]
> For auth gear (i.e. SSO auth handler), it is a user facing endpoint so we should return a user readable message.

so JSON?

---

Actually the original problem I want to solve is VALID_HOSTS problem. If it is misconfigured, auth gear just returns a 400 with empty body. This behavior is too confusing for our early adopters. They keep ask me why they keep getting 400 without anything.

**Comment by kiootic** [comment]
> > For auth gear (i.e. SSO auth handler), it is a user facing endpoint so we should return a user readable message.

> so JSON?

I mean the browser would navigate to this page, so using a plain text, app user readable message would be better. We can use a generic error message and log the detailed error.

> Actually the original problem I want to solve is VALID_HOSTS problem. If it is misconfigured, auth gear just returns a 400 with empty body. This behavior is too confusing for our early adopters. They keep ask me why they keep getting 400 without anything.

We can just add back a plain text message saying so.

**Comment by louischan-oursky** [comment]
> We can just add back a plain text message saying so.

Good. Changing to title of this issue to fix this.
