### ISSUE TITLE
Lack of log for skygear-auth

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#1162]
Version: 002818e

I tried to deploy skygear-auth locally with docker-compose and hand-crafted k8s. When there is mis-config, like `VALID_HOSTS`, or I send the wrong payload format. I don't see any log for me to debug or report the issue accurately.

**Comment by louischan-oursky** [comment]
If you send malformed request, you should be able to see the error in the response.
The `VALID_HOSTS` error is improved in https://github.com/SkygearIO/skygear-server/pull/1145
