### ISSUE TITLE
User `me` action for renewing token and track last usage

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#118]
After https://github.com/SkygearIO/skygear-server/issues/111

We have an `me` endpoint with whoami SDK API. I think the `me` endpoint can do more. I am proposing:

1. Act as token refresh enpoint
1. `me` endpoint will also update the `last_logged_in` refs: https://github.com/SkygearIO/skygear-server/issues/110

Since it is a bit overload of the semantic meaning, it may need some discussion and survey on developer view on this. I think it will be nice to have in MVP instead of calling separate end-point for all above purpose.

**Comment by cheungpat** [comment]
merged in #128

**Comment by rickmak** [comment]
#128 implementation don't renew token.

**Comment by cheungpat** [comment]
interesting, i thought it did!
