### ISSUE TITLE
Allow names to be used for email sender/reply to address

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/skygear-server#1186]
We switched to use JSON schema format validation for emails in tenant config in #1185. However, our format checker does not allows names in email, which developer may want to have for email sender/reply to address. We need special handling for them.

**Comment by louischan-oursky** [comment]
Two formats

1. `addr-spec` 
2. `name-addr`

https://tools.ietf.org/html/rfc2822#section-3.4

**Comment by kiootic** [comment]
The JSON schema `email` format is defined as `addr-spec` of RFC 5322 already, so I'll add a new format `NameEmailAddr` for `name-addr` of RFC 5322.
