### ISSUE TITLE
db.WithContext should rollback the txn in case of panic

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1252]
Rollback the txn in case of panic and propagate the panic.

**Comment by louischan-oursky** [comment]
@carmenlau @kiootic

**Comment by kiootic** [comment]
I don't think it can be done at context. Instead, the middleware (core/middleware.DBMiddleware) should do this (like how it is done for redis).

**Comment by louischan-oursky** [comment]
I guess the reason is TxContext exposes three low-level functions `BeginTx`, `CommitTx` and `RollbackTx` so it is impossible to write a defer statement to rollback on panic. What about removing these 3 low-level functions and require the caller to use `db.WithContext`. It is also a good opportunity to move `db.WithContext` to `TxContext.Do`.

**Comment by louischan-oursky** [comment]
The SafeTxContext can also be embedded into TxContext. It seems that no one is using SafeTxContext.

**Comment by kiootic** [comment]
Sure. To conclude:
- Merge `SafeTxContext` into `TxContext`
- `TxContext` only exposes `Do` function for executing a transaction.

Is this blocking any issue?

**Comment by louischan-oursky** [comment]
No. This is not blocking me. But this is actually a very old bug. It is also quite dangerous because the connection is returned to the pool without being explicitly rolled back or committed. However, what I observed is that the changes are actually committed but I did not figure why.
