### ISSUE TITLE
Unbreak path-only hook URL

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1260]
When Auth Gear has its own domain, the path-only hook URL will be resolved to the host of Auth Gear, not the app.

**Comment by louischan-oursky** [comment]
@kiootic @carmenlau

**Comment by kiootic** [comment]
In my opinion:
- We planned to make auth gear standalone and multi-tenant
- If so, auth gear is the sole responsible party for resolving the path-only URL
- Therefore, it is better that either stop supporting path-only hook URL (personally preferred), or add app domain in tenant config for auth gear use.

Any idea?

**Comment by louischan-oursky** [comment]
> Therefore, it is better that either stop supporting path-only hook URL (personally preferred)

It makes the developer not able to share skygear.yaml with multiple apps. In most case, the developer has multiple apps for different environments.

> add app domain in tenant config for auth gear use.

There is `AppName` in tenant config. If auth gear somehow has the envvar `APP_DOMAIN_FORMAT` that the controller has, auth gear should be able to derive the default app endpoint.

**Comment by kiootic** [comment]
> It makes the developer not able to share skygear.yaml with multiple apps. In most case, the developer has multiple apps for different environments.

I'm considering auth gear as a standalone server, without our gateway and controller. In that case, I think many entry in configuration would also vary with environment, e.g. secrets/keys, app name/id, redirect URIs, so having a different hook URL for different environment is acceptable to me.

**Comment by carmenlau** [comment]
- Update controller to resolve the absolute path for hooks
- Auth gear only accept absolute paths
