### ISSUE TITLE
Auth UI Web App Bugs

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1277]
> the button 'Sign in!' and 'Use email instead' looks different on macOS Chrome, is that ok?
when I tried sign up, it keeps giving 'Invalid email address' error.

> It turns out I entered a email in username field, and it gives invalid email address error. So it's a misleading message. Let's fix it in another PR.

**Comment by louischan-oursky** [comment]
@kiootic 

---

Do you have a screen capture for the button looking different issue?

---

It is the first time I know we cannot use email address for username!

**Comment by kiootic** [comment]
<img width="489" alt="Screenshot 2020-03-24 at 7 04 46 PM" src="https://user-images.githubusercontent.com/6682519/77418789-5dbed980-6e02-11ea-9e34-f562297758e0.png">

I remembered we discussed before that, username cannot be email to enable auto login ID format detection?

**Comment by louischan-oursky** [comment]
> I remembered we discussed before that, username cannot be email to enable auto login ID format detection?

I looked at `login_id_checker.go` and `normalize.go` but did not find the relevant code. Did I miss something?

**Comment by kiootic** [comment]
ref: https://github.com/SkygearIO/features/issues/339

**Comment by louischan-oursky** [comment]
Actually I have been using macos Chrome 80 and did not produce your screenshot. But the layout **does** have problems on Firefox. What Chrome version are you using?

**Comment by kiootic** [comment]
I just tried again and cannot reproduce it too. I've looked into it further, and it seems likely that I was using stale CSS, without the changes in commit 5bcc1d89e058938f061de48e86ffb2f6afc0b7ff.
