### ISSUE TITLE
Avoid using github API in migrate program

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1284]
Install git in the docker image and git clone to get the source.

**Comment by limouren** [comment]
I think downloading a remote tar ball for migration is fine (and good design actually), just that user might not realize that they would hit API limit problem while integrating the migration into their CI / CD pipeline. Either remind the user in documentation or upload the source to other blob storage would resolve this problem.

**Comment by louischan-oursky** [comment]
We considered uploading the source code to blob storage but it seems switching to git clone is simpler.

**Comment by limouren** [comment]
It think it would become another WTF moment when user finds out he cannot run migration because he doesn't have git installed...

**Comment by louischan-oursky** [comment]
The docker image is built by us. It has git installed of course. You probably will not `go run migrate/main.go` from source...
