### ISSUE TITLE
[Auth UI] Adopt Post/Redirect/Get pattern

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1288]
> I just found another potential problem: when I submit a wrong password multiple time when logging in, using the back button in page would result in CACHE_MISS Chrome error.

**Comment by kiootic** [comment]
@louischan-oursky 
Let me try to clarify how to reproduce the bug:
1. Go to Auth UI main page
2. Enter a email and click next
3. Enter a invalid password and click next
4. Error message is visible and password remains filled, click next directly
5. Click the browser back button
6. 'Confirm Form Resubmission' error shown.

**Comment by louischan-oursky** [comment]
Did some research and found [this](https://stackoverflow.com/questions/6833914/how-to-prevent-the-confirm-form-resubmission-dialog).

To fix this problem, we need to adopt the Post/Redirect/Get pattern. In this pattern, if we want to persist state, we only have 2 choices. One is to use cookie while another one is to use URL query parameters.

If we use URL query parameters, the URL would become very long. Some structured data such as `x_error` does not fit into query.

If we use cookie, one approach could be `Set-Cookie` in the redirect response, and pop the cookie in the GET request. Of course, the user cannot perform the POST request concurrently. In most cases a human do not submit a form concurrently.

Thoughts?

**Comment by kiootic** [comment]
In my opinion:
- query is not acceptable, since the state contains sensitive information.
- clearing cookie on GET request would make page refresh does not work.
- storing password is not a good idea in either cookie or query.

**Comment by louischan-oursky** [comment]
We used to have a single endpoint to handle the entire authentication flow. The state is stored in the form hidden fields. In particular, `x_step` stores which step the user is in.

In the new approach, the state is stored in different places.

First, the path determines which step the user is in. The path replaces `x_step`. So `/` redirects to `/login`. `/login` redirects to `/login_password`. `/login` has an anchor to `/signup`. `/signup` redirects to `/signup_password`. 

Other information is stored in cookie. The cookie value is a encoded form. The cookie also stores the step. If the cookie's step does not match the path, then the cookie is cleared. Refreshing the page should work. Pressing back button will cause mismatch in the step value, which effectively is GET without any state.

Password is never stored in either cookie or query because entering password is the final step. If the password is incorrect, only the error is stored in cookie. If the password is correct, the user is authenticated and by Post/Redirect/Get, they will be redirected to `/settings`.
