### ISSUE TITLE
Consider refactor existing SSO RP code

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1297]
We now have `pkg/auth/dependency/oauth` and `pkg/auth/dependency/oidc` which are code for implementing an OP. Maybe it is a good idea to migrate existing SSO RP code to these two packages. Auth UI is becoming a RP so we must reuse the existing code. It is worth refactoring a bit.

@kiootic  Thoughts?

**Comment by kiootic** [comment]
I don't think Auth UI should be counted as RP. In my opinion, auth gear is an Authorization Server, providing OIDC API (for RP) and Auth UI (for user). Optionally, auth gear can act as RP for external IdPs (i.e. social login).

**Comment by louischan-oursky** [comment]
> Optionally, auth gear can act as RP for external IdPs (i.e. social login).

Yes, I am referring to this case.
