### ISSUE TITLE
[Auth] After user create hook not called

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-server#1350]
After migrating to skygear version 9204319edc0c9cc1e4647e7d439b674b5e545e71 with auth ui support, after user create hook is not called

- Skygear Server Date/Version: 9204319edc0c9cc1e4647e7d439b674b5e545e71
- Application Platform: React native
- [x] Is this a regression?

#### Expected Results
After user create hook should be called after sign up with skygear auth ui

#### Actual Results
Hook does not be called

**Comment by kiootic** [comment]
Seems likely related: #1347 

We dispatch after events after transaction commit, so since transaction is not used, no after events are dispatched.
