### ISSUE TITLE
Reorder default login ID keys

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1357]
The order of login ID keys are now important because the first one is the default one in Auth UI.

The order should be `email`, `phone` and `username`.

So in default settings, the user will sign up with email instead of a username.

**Comment by louischan-oursky** [comment]
@carmenlau @kiootic Any objections?

**Comment by carmenlau** [comment]
LGTM:)

**Comment by kiootic** [comment]
I agree!
