### ISSUE TITLE
SameSite=None is unsupported by some old browsers

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1368]
https://github.com/linsight/should-send-same-site-none

https://www.chromium.org/updates/same-site/incompatible-clients

We need some possible workarounds

- Send two Set-Cookie headers for each cookie we want to write. Write a cookie without SameSite=None and then write a cookie with SameSite=None. If the latter is supported, it overwrites the previous one.
- Follow the pseudo code in https://www.chromium.org/updates/same-site/incompatible-clients to determine whether we should write SameSite=None

@carmenlau @kiootic

**Comment by kiootic** [comment]
I think a important point is this in your second link:
> Versions of Safari and embedded browsers on MacOS 10.14 and all browsers on iOS 12. These versions will erroneously treat cookies marked with `SameSite=None` as if they were marked `SameSite=Strict`. This bug has been fixed on newer versions of iOS and MacOS.

That is, the first suggested workaround would not work, since it would be treated as Strict.

**Comment by louischan-oursky** [comment]
Just googled but it seems that there is no Go library implementing https://www.chromium.org/updates/same-site/incompatible-clients :(

**Comment by kiootic** [comment]
For reference on how other framework does it: https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

**Comment by louischan-oursky** [comment]
They ask the framework users to do themselves.
