### ISSUE TITLE
Do not validate host for resolve endpoint

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1437]
Discussed with the team and we have the following conclusions

- https://github.com/SkygearIO/skygear-server/issues/1438
- Do not validate host for resolve endpoint

**Comment by louischan-oursky** [comment]
Since [we do not resolve relative URL now](https://github.com/SkygearIO/skygear-server/commit/63386f0e66185363e19a6a8bf234c216da8002e3), maybe we can even remove validate host middleware. Thoughts?

**Comment by kiootic** [comment]
We're still constructing URLs using `Host` header through `urlprefix.Provider`, so it should not be removed.
