### ISSUE TITLE
Docker-compose up fails on first time

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#145]
(user) got a problem when I run `docker-compose -f docker-compose.yml up` of `skygear-server` first time

```
p_1    | time="2016-09-26T04:17:23Z" level=error msg="Unable to begin transaction for schema migration: dial tcp 172.18.0.3:5432: getsockopt: connection refused" logger=skydb
app_1    | time="2016-09-26T04:17:23Z" level=error msg="Failed to start skygear: failed to open connection: skydb/pq: unable to connect to database because of a network error = dial tcp 172.18.0.3:5432: getsockopt: connection refused"
```

- Skygear Server Date/Version: 0.17.1
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
First run will work.

#### Actual Results
Second run will work.

#### Steps to reproduce

1. Checkout skygear-server
2. `docker-compose -f docker-compose.yml up`

**Comment by cheungpat** [comment]
This is not a regression.

**Comment by cheungpat** [comment]
There are a couple of solutions to this problem:

* change the docker image so that skygear-server will restart on fails
* introduce a delay before skygear-server is run
* skygear-server wait for longer before giving up

pick one
