### ISSUE TITLE
[Auth UI] Handle double click of buttons

### ISSUE THREAD

**Issue by joyzoursky** [SkygearIO/skygear-server#1463]
If user double click on any button (e.g. Next / Disconnect), some events will trigger twice and cause unexpected errors.

- Skygear Server Date/Version: Not sure
- Application Platform: Testing on client app

#### Expected Results
Can disable buttons after click, so user will not click on it for multiple times. Or the server should be able to identify whether it is the same action.

#### Actual Results
Currently it will show some errors like these if user double clicks:
`This identity has been claimed by another user.`
`identity not found`
`unexpected error occurred`

#### Steps to reproduce

1. Click to connect account, e.g. with phone number or email address
2. Enter email or phone number
3. Double click on Next button
4. See unexpected error occurs

#### Screenshots:

<img width=32% src="https://user-images.githubusercontent.com/12539486/83243321-50daaf80-a1d0-11ea-95c1-ac2b81dfc3c4.jpg" /> <img width=32% src="https://user-images.githubusercontent.com/12539486/83243329-5506cd00-a1d0-11ea-9fbf-6113e1533e3a.jpg" /> <img width=32% src="https://user-images.githubusercontent.com/12539486/83243335-5637fa00-a1d0-11ea-86c1-841f3025f286.jpg" /> <img width=32% src="https://user-images.githubusercontent.com/12539486/83243337-56d09080-a1d0-11ea-810b-1764f4b610d8.jpg" /> <img width=32% src="https://user-images.githubusercontent.com/12539486/83243342-57692700-a1d0-11ea-839e-e0327ab43386.jpg" />

**Comment by louischan-oursky** [comment]
This double click issue has to be solved with JavaScript. If JavaScript is disabled, this issue cannot be fixed.
