### ISSUE TITLE
[Auth UI] Should use number keyboard for verification code

### ISSUE THREAD

**Issue by keithtkl** [SkygearIO/skygear-server#1486]
Should use number keyboard for verification code as it is a 4-digit number

- Skygear Server Date/Version: Not sure
- Application Platform: Tested on Rees

#### Expected Results
Display number keyboard when press on the verification code field

#### Actual Results
Text keyboard has been shown when focus on the field

#### Steps to reproduce
1. Signup / Login with email address or phone number
2. On the verification page, click on the code field will see the text keyboard

#### Screenshot
![83748587-05734600-a695-11ea-807f-d67d1edc64bd](https://user-images.githubusercontent.com/10443251/83830293-5c216400-a717-11ea-9eaf-ef2704c3a1cd.jpeg)

**Comment by louischan-oursky** [comment]
Use `<input type="tel">`. `<input type="number">` adds spinner which is very confusing.
