### ISSUE TITLE
Plan for Javascript CloudCode

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-server#149]
Currently Cloudcode support Python only, and there are already numerous request on being able to run Cloudcode with Javascript, I would suggest let's start to plan for Javascript Cloudcode.

**Comment by royuen** [comment]
- #199 - Add lifecycle event to plugin (https://github.com/SkygearIO/skygear-server/issues/199)
- #79 - Support plugin lifecycle event (https://github.com/SkygearIO/py-skygear/issues/79)
- #87 - Cloudcode HTTP transport and return config to server (https://github.com/SkygearIO/skygear-SDK-JS/issues/87)
- #88 - Able to call the cloudcode registered function from server (https://github.com/SkygearIO/skygear-SDK-JS/issues/88)
- #89 - Enable pq connection in cloudcode (https://github.com/SkygearIO/skygear-SDK-JS/issues/89)
- #86 - Cloudcode registry (https://github.com/SkygearIO/skygear-SDK-JS/issues/86)
- #94 - Prepare for docker image (https://github.com/SkygearIO/skygear-SDK-JS/issues/94)
