### ISSUE TITLE
Review tasks to support Firebase Cloud Messaging

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-server#179]

**Comment by cheungpat** [comment]
From what I understand (please correct me if I am wrong), you can use a FCM server key on the GCM protocol. The underlying infrastructure is the same.

[GCM and FCM Frequently Asked Questions](https://developers.google.com/cloud-messaging/faq) says:

> You won’t need to make any server-side protocol changes for the upgrade. The service protocol has not changed. However, note that all new server enhancements will be documented in FCM server documentation.

[Migrate a GCM Client App for Android to Firebase Cloud Messaging](https://developers.google.com/cloud-messaging/android/android-migrate-fcm) says:

> You can update your server code to use new FCM endpoints for sending messages via HTTP and XMPP. Note that the new FCM version of gcm-http.googleapis.com/gcm/ is fcm.googleapis.com/fcm/ (without "http"):
> ...
> Updating these endpoints is not strictly required, as Google will continue to support the existing GCM endpoints.

The same document also mention how to migrate Android app to use Firebase Cloud Messaging, but that only applies on the client side. [iOS here](http://developers.google.com/cloud-messaging/ios/ios-migrate-fcm).

Therefore, I don’t think we need to change the server side to support FCM, but we will need to do this somewhat in the future.

We could do one of this to support FCM on the server side if we want to do it anyway:

* Keep using [go-gcm](https://github.com/google/go-gcm), somehow change the address endpoint to point to FCM. I do not know if this works at all, but [it should be](https://github.com/google/go-gcm/issues/31).
* Add [go-fcm](github.com/NaySoftware/go-fcm), which is another library to send via FCM. The library has a different interface than go-gcm. It does not appears google has a “go-fcm” implementation, which probably says a lot whether we should go this route.
