### ISSUE TITLE
Transient does not work across database boundary

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#21]
I am using the `skygear-server@0.6.1` with `skygear-SDK-JS@0.5.0`.

`query.transientInclude` does not work across database boundary.
That is, if a query is targeted at `privateDB` and the transient target is in `publicDB`, the transient will be `null`
- Skygear Server Date/Version: 0.6.1
- Application Platform: react-native
- [ ] Is this a regression?
- [ ] Attached logs, screenshots
#### Expected Results

It should be legal to include transient target in `publicDB` when issuing a query targeting `privateDB`.
#### Actual Results

The transient is `null`
#### Steps to reproduce

```
const skygear = require('skygear');
const PubTable = skygear.Record.extend('pub_table');
const PrivTable = skygear.Record.extend('priv_table');

const pubRecord = new PubTable();
const privRecord = new PrivTable({
  pub_ref: new skygear.Reference(pubRecord),
});

skygear.publicDB.save(pubRecord)
.then(() => {
  return skygear.privateDB.save(privRecord);
})
.then(() => {
  const q = new skygear.Query(PrivTable);
  q.transientInclude('pub_ref');
  return skygear.privateDB.query(q);
})
.then((records) => {
  const actualResult = records[0]._transient.pub_ref;
  console.log(`pub_ref is ${actualResult}`); // This prints "pub_ref is null"
});
```

**Comment by cheungpat** [comment]
This works as expected.

Querying from the private database will only return data from private database, and querying from the public database will only return data from the public database.

While it is technically possible to implement eager loading of a public DB record through a private DB record, it would be great if you could make a compelling reason for breaking the barrier between a private DB and a public DB.

As an alternative, you can put the private DB record in a public DB and set ACL on the record.

**Comment by chpapa** [comment]
won't fix
