### ISSUE TITLE
Support data type geometry(MultiPolygon,4326)

### ISSUE THREAD

**Issue by lampercy** [SkygearIO/skygear-server#225]
I have a model "District" with a column of "area" of type Postgis MULTIPOLYGON
```js
const District = skygear.Record.extend('district')
const query = new skygear.Query(District)
skygear.publicDB.query(query)
>> POST http://192.168.99.100:3000/record/query 500 (Internal Server Error)
```
it will throw error when i query them

**Comment by cheungpat** [comment]
The type is not supported.

cc @rickmak

**Comment by rickmak** [comment]
I suppose you use it at plugin and don't need the MULTIPOLYGON at client. Will a skip of specific keyPath will works? @lampercy 
I don't think we will support all field type in SDK.

**Comment by rickmak** [comment]
@lampercy please checkout https://github.com/SkygearIO/skygear-server/pull/236 and https://github.com/SkygearIO/skygear-server/issues/231

Is it enough for your use-cases?
