### ISSUE TITLE
Add CORS support for skygear assets

### ISSUE THREAD

**Issue by akiroz** [SkygearIO/skygear-server#226]
Skygear currently doesn't support adding CORS headers for assets.

This is useful for apps that uses the HTML5 canvas with images hosted as skygear assets.
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by chpapa** [comment]
If I want to suggest that besides setting environment variables / command line, maybe we can also have this option on portal.skygear.io, how shall I do it? Open another issue?

**Comment by cheungpat** [comment]
This primary concerns with cloud assets, which is a Skygear Cloud feature.

We will add CORS headers to cloud assets so that you can access cloud assets in cross origin requests. You’ll need to host your web site under `*.skygear.io` though.

**Comment by cheungpat** [comment]
Both `asset.skygeario.com` and S3 now returns CORS headers.
