### ISSUE TITLE
Check if an unsupported data type is queried, make sure the error message is understandable

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-server#231]
- JS SDK
- iOS SDK
- Android SDK

**Comment by cheungpat** [comment]
The following error is returned from skygear when the database contains a column with the type `money`:

```json
{
  "error": {
    "name": "UnexpectedError",
    "code": 10000,
    "message": "received unknown data type = money for column = money"
  }
}
```

This is what the user will see:

![Uploading Screen Shot 2016-11-17 at 2.23.17 PM.png…]()

**Comment by royuen** [comment]
- [ ] If the column is not supported, the record should still be returned, and that column will have a specific json notation to specify this is unsupported and thus there is no value.
