### ISSUE TITLE
Returned date format that lead iOS SDK crash

### ISSUE THREAD

**Issue by a821246710** [SkygearIO/skygear-server#237]
Returned date format that lead iOS SDK crash

- Skygear Server Date/Version: 0.19.1 
- Application Platform: iOS

#### Expected Results
date format: 2016-11-19T16:00:00.000000Z

#### Actual Results
date format: 2016-11-19T16:00:00Z

#### server request and response Log:

app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="POST /record/query" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="------ Header: ------" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Accept-Encoding: [gzip, deflate]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Content-Type: [application/json]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Content-Length: [150]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Accept-Language: [en-us]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Accept: [application/json]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Connection: [keep-alive]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="User-Agent: [moovupseeker/1 CFNetwork/808.1.4 Darwin/16.1.0]" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="------ Request: ------" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="{\"record_type\":\"just test\",\"database_id\":\"_public\",\"action\":\"record:query\",\"access_token\":\"47a1b6c2-78f9-4736-b981-9ae12ae14147\",\"api_key\":\"changeme\"}" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Opening DBConn: {pq moovup postgresql://postgres:@db/postgres?sslmode=disable}" logger=preprocessor 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Get DB OK" logger=preprocessor 
app_1                 | time="2016-11-23T03:39:01Z" level=warning msg=9e13446a-3c48-4b67-82ec-13522372bd47 logger=skydb 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Executed SQL with sql.QueryRowx" args=[9e13446a-3c48-4b67-82ec-13522372bd47] executionCount=1 logger=skydb sql="SELECT id, username, email, password, auth, token_valid_since, last_login_at, last_seen_at, array_to_json(array_agg(role_id)) AS roles FROM \"app_moovup\".\"_user\" LEFT JOIN \"app_moovup\".\"_user_role\" ON id = user_id WHERE id = $1 GROUP BY id" 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Querying remoteColumnTypes just test" logger=skydb 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Executed SQL with sql.QueryRowx" args=[just test app_moovup] executionCount=2 logger=skydb sql="\nSELECT c.oid\nFROM pg_catalog.pg_class c\n     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace\nWHERE c.relname = $1\n  AND n.nspname = $2" 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Executed SQL successfully with sql.Queryx" args=[201128] error=<nil> executionCount=3 logger=skydb sql="\nSELECT a.attname,\n  pg_catalog.format_type(a.atttypid, a.atttypmod)\nFROM pg_catalog.pg_attribute a\nWHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped" 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Executed SQL successfully with sql.Queryx" args=[app_moovup just test] error=<nil> executionCount=4 logger=skydb sql="SELECT kcu.column_name, ccu.table_name FROM information_schema.table_constraints AS tc JOIN information_schema.key_column_usage AS kcu ON tc.constraint_name = kcu.constraint_name JOIN information_schema.constraint_column_usage AS ccu ON ccu.constraint_name = tc.constraint_name WHERE constraint_type = 'FOREIGN KEY' AND tc.table_schema = $1 AND tc.table_name = $2" 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Cache remoteColumnTypes just test" logger=skydb 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="Executed SQL successfully with sql.Queryx" args=[9e13446a-3c48-4b67-82ec-13522372bd47 ] error=<nil> executionCount=5 logger=skydb sql="SELECT \"just test\".\"_created_at\" as \"_created_at\", \"just test\".\"_created_by\" as \"_created_by\", \"just test\".\"_updated_at\" as \"_updated_at\", \"just test\".\"a_date\" as \"a_date\", \"just test\".\"_database_id\" as \"_database_id\", \"just test\".\"_access\" as \"_access\", \"just test\".\"_updated_by\" as \"_updated_by\", \"just test\".\"_id\" as \"_id\", \"just test\".\"_owner_id\" as \"_owner_id\" FROM \"app_moovup\".\"just test\" WHERE (_access @> '[{\"user_id\": \"9e13446a-3c48-4b67-82ec-13522372bd47\"}]' OR _owner_id = $1 OR _access @> '[{\"public\": true}]' OR _access IS NULL) AND \"just test\".\"_database_id\" = $2" 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="------ Response: ------" logger=router 
app_1                 | time="2016-11-23T03:39:01Z" level=debug msg="{\"result\":[{\"_access\":[{\"level\":\"read\",\"public\":true}],\"_created_at\":\"2016-11-23T02:33:25.91746Z\",\"_created_by\":\"9e13446a-3c48-4b67-82ec-13522372bd47\",\"_id\":\"just test/59C8251A-4887-4189-8BCD-5ED9F7AE56A6\",\"_ownerID\":\"9e13446a-3c48-4b67-82ec-13522372bd47\",\"_type\":\"record\",\"_updated_at\":\"2016-11-23T02:33:25.91746Z\",\"_updated_by\":\"9e13446a-3c48-4b67-82ec-13522372bd47\",\"a_date\":{\"$date\":\"2016-11-19T16:00:00Z\",\"$type\":\"date\"}},{\"_access\":[{\"level\":\"read\",\"public\":true}],\"_created_at\":\"2016-11-23T03:04:17.943615Z\",\"_created_by\":\"9e13446a-3c48-4b67-82ec-13522372bd47\",\"_id\":\"just test/A778B4B6-5192-47CC-B068-38AC630AABA4\",\"_ownerID\":\"9e13446a-3c48-4b67-82ec-13522372bd47\",\"_type\":\"record\",\"_updated_at\":\"2016-11-23T03:04:17.943615Z\",\"_updated_by\":\"9e13446a-3c48-4b67-82ec-13522372bd47\",\"a_date\":{\"$date\":\"2016-11-19T16:00:01Z\",\"$type\":\"date\"}}]}\n" logger=router

**Comment by cheungpat** [comment]
The format `2016-11-19T16:00:00Z` is causing problem on the iOS side because it does not have sub-second digits.

**Comment by cheungpat** [comment]
I think this fix will come in two parts:

* skygear-server will return date/time in a consistent format, not dependent of whether sub-second precision is needed
* iOS SDK should parse two formats: the date/time with sub-second precision and the other without

**Comment by cheungpat** [comment]
The issue should be fixed in skygeario/skygear-iOS-SDK#66 and the server implementation will be fixed in #240
