### ISSUE TITLE
Conditional save predicate

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#242]
Purpose: The conditional save predicate is used by the client to specify conditions in which a record should be saved. Conditions are evaluated by the server.

Proposal: `record:save` request to have a new attribute that state the predicate for which the record should be saved if the existing record satisfy the predicate (in other words, “satisfy” means a query of that predicate will return the record).

Example: a record is only saved if date is null:

```
{ "action": "record:save",
  "records": [{
    "_save_predicate": {"eq", "date", null},
    "_id": "note/abc"
}]}
// or
{ "action": "record:save",
  "predicate": {"eq", "date", null}",
  "records": [/* ... */]
}
```

**Comment by chpapa** [comment]
I guess it is duplicated with #123 ?

**Comment by chpapa** [comment]
Moved to skygeario/features#11
