### ISSUE TITLE
Simplify records needs a user to query/update via cloud functions

### ISSUE THREAD

**Issue by david90** [SkygearIO/skygear-server#261]

**Comment by royuen** [comment]
- [ ] Improve generate access token (portal: can choose will or will not expire, JWT)
- [ ] Write guide for generate access token for cloud usage
- [ ] If login with master key, it will login as "master-key-user" user. All recording saving will be belonging to this "master-key-user" user.

**Comment by chpapa** [comment]
This issue is tightly related with Skygear Portal / [skycli](https://github.com/skygeario/skycli for actual usage.

So when @b123400 work on this issue, what are the client side deliverables are we expecting? Or no deliverables on client side? (In that case, can we create those issues in skygear portal / skycli and ref here?)

If the deliverable include portal, we will need some design?

**Comment by chpapa** [comment]
Discussed again with @b123400 @rickmak and @ben181231 

1. Why we need another access token? We already have asUserId in CloudContainer which allow Cloud Functions call with User ID to "switch" to another user immediately. Ref: https://docs.skygear.io/guides/cloud-function/calling-skygear-api/python/#using-the-master-key
2. We can still have master_key default user. @b123400 think it is too much constraint for developers to lose control to one username.

Agreement so far:

1. We will check with @david90 again to see if asUserID is good enough.
2. We will still implement the Cloud Functions call, when called with MasterKey, will access the Database as a Master Key God User.

Any comments? @david90 @cheungpat

**Comment by chpapa** [comment]
@david90 responded said asUserID is actually good enough...

I'm actually thinking if we really need to implement the master key thing.....? Would that really help?

**Comment by ben181231** [comment]
I think adding Master Key God User increases the difficulties for developers to understand the whole auth mechanism since it is adding another exceptional case for the auth and ACL mechanism.

**Comment by b123400** [comment]
After discussing on Slack, the conclusion is creating a god user when the request is using the master key and no user auth is present

**Comment by rickmak** [comment]
May @david90 provide a use-case?

**Comment by david90** [comment]
For example in a cron job:
1) the job is to fetch the latest 50 notes and push to slack.
2) the job is to fetch the latest 50 notes of the user and push to slack.

**Comment by chpapa** [comment]
Am I correct that in the use cases @david90 suggested, you just wish to save the notes as some users, but don't care whose?

In those cases, which approach is the best? (Master API = god user, asUserID is enough, or others...?)

**Comment by cheungpat** [comment]
> Am I correct that in the use cases @david90 suggested, you just wish to save the notes as some users, but don't care whose?

I am confused, @david90 was talking about “fetch the latest 50 notes”, but @chpapa is talking about “save the notes as some users”. Can @david90 elborate with his use cases?

**Comment by chpapa** [comment]
@cheungpat Oh it is because:

1. Originally the problem was "when you save records, you need to sign up / login, and the code logic is too complicated" (refer to the issue title)

2. And @david90 mentioned "fetch the latest 50 notes", so it seems logically only possibility is it needs to cache (save) the notes.

Hence the question

> Am I correct that in the use cases @david90 suggested, you just wish to save the notes as some users, but don't care whose?

**Comment by cheungpat** [comment]
> so it seems logically only possibility

@chpapa I am sorry I still couldn’t connect the dots. I suppose my logic does not work the same as you do.

Would be great if @david90 could elaborate a bit on his use cases.

**Comment by david90** [comment]
The major problem now is user will need to do auth before update/query the records. That would make the cloud code logic more complex than it should be.

Yes, I think we just nee to provide ways to save the notes as some users directly. Master Key sounds good enough for this purpose.

**Comment by cheungpat** [comment]
@rickmak Is the information provided by @david90 enough for you to draft a plan?
