### ISSUE TITLE
Support PostGIS GeoJSON and ST_Contains

### ISSUE THREAD

**Issue by lampercy** [SkygearIO/skygear-server#262]
### To save polygon
```
const polygon = new skygear.GeoJSON({
  "type": "Polygon",
  "coordinates": [[
    [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]
  ]]
});
```

### To search geometry by location
```
const query = new skygear.Query(District);
const geoLocation = new skygear.Geolocation(22.283, 114.15);
query.containsValue('area', geoLocation);
```

### To search location by geometry
```
const place = new Place({
  name: 'IFC HK',
  location: geoLocation,
});
skygear.publicDB.save(place);

const query = new skygear.Query(Place)
query.contains('location', polygon); 
```

### To search geometry by geometry
```
const query = new skygear.Query(District);
query.containsValue('area', polygon);
```

### Point
```
{
  "type": "Point", 
  "coordinates": [102.0, 0.5]
}
```

### LineString
```
{
  "type": "LineString",
  "coordinates": [
    [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
  ]
}
```

### Polygon with interior rings
```
{ "type": "Polygon",
  "coordinates": [
    [[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
    [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]
  ]
}
```

### Multipolygon
```
{ "type": "MultiPolygon",
  "coordinates": [
    [[[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]],
    [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
     [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]]
    ]
}
```

**Comment by cheungpat** [comment]
You also need to wrap the GeoJSON object into a skygear value type object.

A few examples: https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/skydb/skyconv/map.go

Perhaps something like `{"$type": "geojson", "$value": {"type": "MultiPolygon" /* ... */}}`.

**Comment by lampercy** [comment]
yes, it is exactly what I want to do

**Comment by cheungpat** [comment]
I am going to take over this pull request. If @lampercy or @rickmak have any work not pushed, this would be a great time to push your work for inclusion.

**Comment by rickmak** [comment]
I don't have extra work on hand. Just wonder will you implement query. Or just merge the Read/Write PR first https://github.com/SkygearIO/skygear-server/pull/272

**Comment by cheungpat** [comment]
I am going to create a feature branch off the current master, merge all the changes on this feature branch to it (producing a merge commit), then add my work on it.
