### ISSUE TITLE
Unable to send cert based APNS push notification after updating to v0.21.1

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-server#270]
From v0.19 to v0.21.1

Kept using cert based APNS configuration as before. After upgrade, no configuration changed, it returns following error after sending an APNS push notification:

```
Failed to send push notification: Post https://api.push.apple.com/3/device/1d5eaa98b393c6a08832ff597ed943898c14eb68b7d9ae61ed3e00293696f9a7: remote error: internal error
```

Error log - https://sentry.io/oursky/village-skygear-go-staging/issues/206824995/

Observation:
- It works in local dev, which is using sandbox mode
- It doesn't work on staging server, which is using production mode

Reviewed configuration and doesn't find problem. Also tried to set the type explicitly to 'cert' but still doesn't work

**Comment by cheungpat** [comment]
It appears the cert is expired.
