### ISSUE TITLE
Abort the DB connection on API timeout

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#277]
This is a follow up of #271.

The API will time out now. But the respective DB connection will not abort, but waiting the DB connection to return.  In the case of deadlock, the DB connection will not return and the resource will hold up. It will be better for skygear-server to actively abort the long running DB connection.

**Comment by cheungpat** [comment]
Golang support cancelable queries in go1.8

**Comment by rickmak** [comment]
go1.8 is scheduled to be released on Feb 14th/15th/16th

refs: https://groups.google.com/forum/#!topic/golang-dev/G09HaWfMl6g

**Comment by cheungpat** [comment]
first step: #282

**Comment by cheungpat** [comment]
https://github.com/golang/go/releases/tag/go1.8

**Comment by cheungpat** [comment]
fixed in #366
