### ISSUE TITLE
Revisit default behavior for record ACL

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#283]
It appears there are confusion as to the ACL behavior when `_access` is `null`.

According to [skydb/record.go](https://github.com/SkygearIO/skygear-server/blob/a6ddba02ca34a949f8c7afbdd2967db08918b66c/pkg/server/skydb/record.go#L171), the access is granted by default if ACL is empty (`null` becomes empty slice in golang).

Therefore the equivalent ACL when `_access` is `null` is world writable.

There are two options for how to approach this issue:

* skygear developers think the default ACL for `_access = null` should be public readable. Adopting this behavior will be a breaking change as there are apps that rely on the implemented behavior.
* keep the implemented behavior that `_access = null` means global writable, update the SDKs to reflect this default.

**Comment by royuen** [comment]
- [ ] Update to public read if ```null```
- [ ] Check all SDK behaviour when seeing ```_access = null```
- [ ] Update API doc to include ```_access = null``` behaviour

**Comment by cheungpat** [comment]
I think this issue is closed prematurely as the fundamental question of what `access = null` means is not addressed.

**Comment by cheungpat** [comment]
It is agreed that the `access=null` means public-readable instead of public-writable. See #359.
