### ISSUE TITLE
Lambda function returning actual data even without API Key

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-server#301]
Lambda function returning actual data even without API Key

- Skygear Server Date/Version:  0.22.1 (on skygeario.com)
- Application Platform: cloud functions

#### Expected Results
HTTP 401

#### Actual Results
HTTP 200, with actual data

#### Steps to reproduce
 - Create Lambda function "dev:a". So it actually have and endpoint at https://MASKED.skygeario.com/dev/a
 - Submit the POST request directly with body {"args":["arg0"]} (without API key)
 - Receive the data successfully without auth

is "user_required=True" means "require user sign in" or "require API key"?

> If user_required is set to True, only authenticated user can call this function. Skygear will return an PermissionDenied error if an unauthenticated user tries to call this function.

Or I misunderstand the term "authenticated user"? It actually means "authenticated request"?

**Comment by chpapa** [comment]
@rickmak did you verified this problem 21 days ago?

**Comment by rickmak** [comment]
@seventhmoon "user_required=True" means "require user sign in" . When you specified `user_required=True` the request payload will require a valid `access_token` value. As following:

```
{
    "access_token": "acquired it by login",
    "action": "dev:a",
    "name": "kitty"
}
```

The full curl will be like this: `curl http://localhost:3000/ -d '{"access_token": "acquired it by login","action": "dev:a","args": ["arg1"]}'`

From the step you provided. You are POST to the `https://MASKED.skygeario.com/dev/a`. Lamdba is not `handler`, it is not matched by PATH in URL. Lambda dispatch depends on the `action` value in the payload. i.e. `/dev/a` in URL does not work with lambda. The path only work on `handler`.

**Comment by chpapa** [comment]
May @seventhmoon help confirm? It would be interesting if you set up a Lambda Function but ends up successfully return data from a HTTP endpoint. Or send me the endpoint you're testing with privately/here?

**Comment by seventhmoon** [comment]
@rickmak I did inspect the traffic in the sample app and this is how lambda function in Android communicate with server.

Just like the sample function @skygear.op('food:buy') will create an endpoint /food/buy on the server.
However, I found that API Key is not required for accessing this endpoint.

**Comment by seventhmoon** [comment]
@chpapa 

```
@skygear.op('food:buy')
def buy_food(food):
    # return an object to the SDK
    return {
        'success': True,
        'food': food,
    }
```

```
curl -i -H "Content-Type: application/json" -d '{"args":["apple"]}' https://testing3.skygeario.com/food/buy
HTTP/1.1 200 OK
Server: nginx/1.11.9
Date: Wed, 29 Mar 2017 06:07:59 GMT
Content-Type: application/json
Content-Length: 43
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *

{"result":{"food":"apple","success":true}}
```

**Comment by rickmak** [comment]
@seventhmoon we have two parameter: `user_required ` and `key_required`

Following decoration will required `api_key` to be presented in request.

```
@skygear.op('food:buy', key_required=True)
def buy_food(food):
    # return an object to the SDK
    return {
        'success': True,
        'food': food,
    }
```

Missing api_key will result following response:

```
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json
Server: Skygear Server/0.22.1-61-gd189218
Date: Wed, 29 Mar 2017 06:45:02 GMT
Content-Length: 101

{"error":{"name":"NotAuthenticated","code":101,"message":"Both api key and access token are empty"}}
```

The relation of `user_required ` and `key_required` are as follow:

1.  When `key_required=True`, either present of valid `api_key` or `access_token` will pass through the authorization
2. When `user_required=True`, present of valid `access_token` is required.
3. If you specific a lambda with both `key_required=True` and `user_required=True`, present of valid `access_token` is required. `api_key` present or not will not matters. i.e. `user_required` will override `key_required`
4. So when both `key_required=False` and `user_required=False`, the API will be publicly callable.

**Comment by seventhmoon** [comment]
@rickmak understood.
Waiting for an update for the [doc](https://docs.skygear.io/guides/cloud-function/lambda/python/)

**Comment by rickmak** [comment]
We just merged, it will be release to http://docs.skygear.io soon. https://github.com/SkygearIO/guides/pull/45
