### ISSUE TITLE
Support many-to-many relations better

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-server#325]
This is a meta issue to discuss the pattern and use cases for many-to-many relations.

## Idea
Approach A. Store array of references in each record
Approach B. Create an intermediate record

### Approach A
1. Able to query for objects in the array, and return only subset of results.
2. Able to add / remove objects in the array without fetching the whole array (when it is huge)

**Comment by samuelplaymore** [comment]
Approach A

I have create a Class extends Array, and use it as the following now:
`newBook.notes = new Skygear.ReferenceArray(noteObject, 'note/6430a3a6-0882-40dd-8d3a-650c9fa48ed1');`
OR
`newBook.notes = new Skygear.ReferenceArray([noteObject, 'note/6430a3a6-0882-40dd-8d3a-650c9fa48ed1']);`

And it will finally save it as `['note/id1', 'note/id2']` in DB.

Therefore, I can use `query.containsValue('notes',noteObject);` OR `query.containsValue('notes','note/id1');` to filter it.

PS: it need to modify / overwrite in containsValue for supporting pass object as 2nd arg.

**Comment by samuelplaymore** [comment]
##Approach B

I think we can take a reference from Parse.Relation.
It also save an intermediate class dynamically.

Take a look with the following 3 classes in Parse and MongoDB.
`_User, _Role, _Join:users:_Role`

**Comment by chpapa** [comment]
Referencing similar suggestions at SkygearIO/skygear-SDK-Android#103

**Comment by chpapa** [comment]
Thanks for comments @samuelplaymore ; Feel free to help proposing something (even sending PR 😆 ) or we might discuss these in next product meeting and see if you're interested to participate in.

**Comment by chpapa** [comment]
Moved meta issue to SkygearIO/features#8
