### ISSUE TITLE
Missing asset content type in response of record save

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-server#327]
When save a record with asset typed field, `$content_type` of the field is expected. Actual, it returns empty string.

```shell
$ curl \
-X POST \
-H "Content-Type: application/json" \
-d '{
    "action": "record:save",
    "api_key": "changeme",
    "access_token": "***",
    "database_id": "_public",
    "records": [
    	{
    		"_id": "Demo\/001",
    		"_access": [
    			{
    				"public": true,
    				"level": "read"
    			}
    		],
    		"img": {
    			"$type": "asset", 
    			"$name":"dabfeed9-6993-4130-a825-9f010b037ce7-Record-Image",
    			"$content_type":"image\/jpeg",
    			"$url":"http:\/\/localhost:3001\/files\/dabfeed9-6993-4130-a825-9f010b037ce7-Record-Image"
    		}
    	}
	]
}
' "http://localhost:3001/" | python -m json.tool

{
    "result": [
        {
            "_access": [
                {
                    "level": "read",
                    "public": true
                }
            ],
            "_created_at": "2017-03-22T09:37:54.622852Z",
            "_created_by": "7546ea5a-f993-4592-b274-45a2bc6c54bc",
            "_id": "Demo/001",
            "_ownerID": "7546ea5a-f993-4592-b274-45a2bc6c54bc",
            "_type": "record",
            "_updated_at": "2017-03-22T09:47:19.185657Z",
            "_updated_by": "7546ea5a-f993-4592-b274-45a2bc6c54bc",
            "img": {
                "$content_type": "",
                "$name": "dabfeed9-6993-4130-a825-9f010b037ce7-Record-Image",
                "$type": "asset",
                "$url": "http://localhost:3001/files/dabfeed9-6993-4130-a825-9f010b037ce7-Record-Image"
            }
        }
    ]
}
```

**Comment by rickmak** [comment]
@b123400 we will need this issue to make a minor release. Do you think it can be done by tomorrow? Than I will merge the zmq-multiplex to master.

**Comment by b123400** [comment]
Fixed, though I think it is not completely what you are expecting.

There are 2 issues here:

1. Despite the content of the request, the server wasn't returning `$content_type`. e.g. You don't need to specify "img" in the above request body, the bug still happens.
2. Record's assets are not updated accordingly. (e.g. The "$content_type" you specified in the payload is not going to update the value in database)

I have fixed (1), but not (2).
We currently have a separated API `asset:put` for creating asset, seems not very good to mix asset update in `record:save`.

Which means after this PR, you should see behaviour like this:
1. Upload asset with `$content_type: "text/plain"`
2. Use `record:save` to change the content type to "application/json"
3. The response of the above request will be "text/plain"

**Comment by ben181231** [comment]
> We currently have a separated API `asset:put` for creating asset, seems not very good to mix asset update in `record:save`.

Agree on this. For `record:save`, only `$type` and `$name` fields in the asset are respected, other fields will be ignored.
