### ISSUE TITLE
Distinguish between no-permission and not logged in

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-server#330]
Can we show a different error message (could use same error code) for the following two situations:
- logged in but no permission
- logged out.

e.g. currently it would show "No permission to query user" 

But some new users don't understand Skygear need to login for any DB operation, so it is better to give them a meaningful message like "Need to login user for a DB operation, no permission to query user"

**Comment by cheungpat** [comment]
> e.g. currently it would show "No permission to query user"

Is this a client SDK error or is this a server error. I suspect that this message comes from an SDK.

I recommend that you check out the list of [skygear-server error codes](https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/skyerr/skyerr.go), which have fine-grained error codes for different access denied scenarios:

	// NotAuthenticated is for operations that requires authentication
	// but the request is not properly authenticated.
	NotAuthenticated ErrorCode = 101 + iota

	// PermissionDenied occurs when the requested resource or operation
	// exists, but the request is not allowed for some reason.
	PermissionDenied

	// AccessKeyNotAccepted occurs when the request contains access key
	// (API key), but the access key is not accepted.
	AccessKeyNotAccepted

	// AccessTokenNotAccepted occurs when the request contains access token
	// but the access token is not accepted.
	AccessTokenNotAccepted

	// InvalidCredentials occurs when the information supplied by a user
	// to get authenticated is incorrect.
	InvalidCredentials

If the client has an access token and the access token was used to log out a session, it means the access token is not accepted by the server. In this case the error is `AccessTokenNotAccepted`. It is the job of the SDK to display a human readable error message for that error.

If you seen the above error message from the Android SDK, there is [another issue](https://github.com/SkygearIO/skygear-SDK-Android/issues/89) which could be related. I recommend that you check out that issue so to identify if the problem you are facing is a client SDK or server problem.
