### ISSUE TITLE
Plugin HTTP handler or Lambda not getting called, after triggering after_save with async=True

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/skygear-server#347]
Skygear Server Date/Version: v0.22.1, python plugin with zmq

#### Steps to reproduce

1. client call save record
2. trigger after_save in plugin
3. client call http handler or lambda
4. the handler function is not called
5. plugin time out after a while

Methods to make the handler work:
either:
- use http instead of zmq
- set async=False

**Comment by Steven-Chan** [comment]
plugin:
```python
import logging
import skygear

log = logging.getLogger(__name__)


@skygear.handler('handler', method=['POST'])
def handler(req):
    return {
        'result': 'handler is OK'
    }


@skygear.after_save('recordA', async=True)
def recordA_async_after_save(record, original_record, conn):
    log.info('recordA_async_after_save')
```

client.js
```js
const skygear = require('skygear');
const agent = require('superagent');

const RecordA = skygear.Record.extend('recordA');

skygear.config({
  'apiKey': 'apikey',
  'endPoint': 'http://localhost:3003/',
}).then(() => {
  return skygear.signupAnonymously();
}).then(() => {
  const r = new RecordA({ 'content': 'Hello World' });
  return skygear.publicDB.save(r, {atomic: true});
}).then(() => {
  console.log('save success');
  agent.post('http://localhost:3003/handler').end((err, res) => {
    if (err) {
      console.log('http handler err');
    } else {
      console.log('http handler success');
    }
  });
}).catch(() => {
  console.log('save failed');
});
```

**Comment by b123400** [comment]
Cause identified.

[ZMQ broker expect the response channel to be consumed.](https://github.com/SkygearIO/skygear-server/blob/6f651fba7b39c6359b6055b85d087142ee0491d4/pkg/server/plugin/zmq/broker.go#L220-L230)
[zmqTransport does not always consume response channel.](https://github.com/SkygearIO/skygear-server/blob/6f651fba7b39c6359b6055b85d087142ee0491d4/pkg/server/plugin/zmq/rpc.go#L162-L172)

When a request is ended before async handler responds, transport gives up consuming from broker. Broker keeps waiting for the channel to be consumed.

Working on a fix.

**Comment by chpapa** [comment]
@Steven-Chan Can you help verify the pull request fixed your issue? If yes please close it.

**Comment by rickmak** [comment]
Steven verified it is fixed.
