### ISSUE TITLE
Write Spec for General SSO login (with Facebook and Google Login as Reference)

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-server#350]
Write the spec at SkygearIO/features#5

**Comment by cheungpat** [comment]
@tensiuyan Currently auth provider is able to do this:

* Login with auth provider.
* Add another auth provider user to the current account. (e.g. “Add Facebook to your existing account”)

So basically if you login with a social account, a new account is created when the social account is not associated with anything. Therefore the auth provider function does not check the email address.

Do you mean that if a user have Facebook and Google both with `abc@example.com` email address, the skygear should notice this and do something different?

**Comment by tensiuyan** [comment]
@cheungpat I think I kinda mixed up server level and API level items. I will clean it up after the product meeting 🙏

**Comment by chpapa** [comment]
@cheungpat I think Skygear should have ways to tackle the following situation: (as written on  SkygearIO/features#5)

1. Login by AuthProvider A, but the email already got another account from AuthProvider B, show an error and tell users to login with another AuthProvide B
2. Login by AuthProvider A, but the email already got another account from AuthProvider B, tell users it is already merged.
3. Login by AuthProvider A, but the email already got another account from AuthProvider B, assume it is two different accounts.
