### ISSUE TITLE
Write spec for auto anonymous user session

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-server#351]
Write spec here skygeario/features#14

**Comment by cheungpat** [comment]
This looks more like an SDK feature instead of a Server feature. This is because the client side knows whether there is a user session when the client calls CloudDB features.

**Comment by chpapa** [comment]
Agree, and this issue need more design on the API level and think carefully for the implication too. I'm writing something at SkygearIO/features#14

**Comment by tensiuyan** [comment]
@cheungpat @chpapa Sure. I leave the it for discussion at the product meeting first.

**Comment by rickmak** [comment]
Close and follow up at features repo.
