### ISSUE TITLE
Call oauth_add for adding social networks to user

### ISSUE THREAD

**Issue by b123400** [SkygearIO/skygear-server#356]
- Add new handler `auth:access_token`
- accepts an access token and user_id
- then call provider to handle them (https://github.com/SkygearIO/py-skygear/issues/138)

**Comment by rickmak** [comment]
Merge?

Do you mean adding another authentication method for a user?

It actually doesn't merge anything. Adding multiple auth methods to a user is not merging accounts.

**Comment by b123400** [comment]
Yes sorry, bad naming

**Comment by chpapa** [comment]
Hmmm, I think it should also be something on the client SDK? like `container/user.signInWithNewAuthProvider` something like that?

**Comment by b123400** [comment]
Yeah, that seems convenient

**Comment by b123400** [comment]
Not relevant after revising the SSO proposal
