### ISSUE TITLE
[OAuth] Add new provider API for connecting any OAuth compatible service

### ISSUE THREAD

**Issue by b123400** [SkygearIO/skygear-server#357]
connect https://github.com/SkygearIO/features/issues/5
connect https://github.com/SkygearIO/py-skygear/issues/138

### API for integrating other services

- New decorator `@skygear.provides("oauth", <provider id>)`
  - Register a new class that returns urls for OAuth flow
  - Example in the above session
  - The goal is to let users to integrate any website that support OAuth

The plugin internally has a "Map<ProviderID, (info -> URL)>" map, something like this.
It will be used to generate urls when user auth.

```
{
  'com.facebook': {
    'auth': () =>
        "https://www.facebook.com/v2.9/dialog/oauth" +
        "?client_id=" + clientID +
        "&redirect_uri=" + generateRedirectURL()
    'access_token': (code)=>
        "https://www.facebook.com/v2.9/dialog/access_token" +
        "?client_id=" + clientID +
        "&client_secret=" + FACEBOOK_CLIENT_SECRET
  },
  'com.google': {
    'auth': ...,
    'access_token': ...
  }
}
```

Since the map is in plugin, user should be able to extend it easily.

```
@skygear.provides("oauth", "com.facebook")
class FacebookOAuthProvider
  def auth_url(self):
    return "http://example.com/auth"

  def access_token_url(self, code):
    return "http://example.com/access_token?code="+code

  def refresh_token_url(self, refresh_token):
    return "http://example.com/token?grant_type=refresh_token&refresh_token=" + refresh_token
```

**Comment by rickmak** [comment]
I am not sure why this issue is at skygear-server. What is the actionable item?

**Comment by carmenlau** [comment]
Replaced by #459
