### ISSUE TITLE
Create field-based ACL model

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-server#375]
Refer to the [field-based ACL feature](https://github.com/SkygearIO/features/blob/master/features/48-user-profile-discovery/field-based-acl.md), this issue includes:

- Models related to field-based ACL (no need to take effect in this issue):
  - Accessibility levels (`ReadWrite`, `ReadOnly` and `NoAccess`)
  - Discovery levels (`Queryable`, `Discoverable` and `NotQueryable`)
  - Field-based Access Control Entity
  - User Roles
- Database migration
- Endpoints for field-based ACL:
  - Getting field-based ACL
  - Updating field-based ACL

**Comment by cheungpat** [comment]
I will take care of the model and database migration first and handle the endpoints later.
