### ISSUE TITLE
follow linux-setup.md can't download server package

### ISSUE THREAD

**Issue by yuchangfu** [SkygearIO/skygear-server#383]
curl -s -L https://github.com/SkygearIO/skygear-server/releases/latest | egrep -o '/SkygearIO/skygear-server/releases/download/[v.0-9]*/skygear-server-linux-amd64' | wget --base=http://github.com/ -i - -O skygear

can't download server package.
I got this error:
--2017-06-14 15:05:24--  http://github.com/SkygearIO/skygear-server/releases/download/v0.24.0/skygear-server-linux-amd64
Resolving github.com (github.com)... 192.30.255.113, 192.30.255.112
Connecting to github.com (github.com)|192.30.255.113|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/SkygearIO/skygear-server/releases/download/v0.24.0/skygear-server-linux-amd64 [following]
--2017-06-14 15:05:26--  https://github.com/SkygearIO/skygear-server/releases/download/v0.24.0/skygear-server-linux-amd64
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-14 15:05:28 ERROR 404: Not Found.

**Comment by cheungpat** [comment]
@yuchangfu Thanks for reporting the issue! Let me fix that.

**Comment by cheungpat** [comment]
@yuchangfu This is fixed! Please check out the updated installation guide.
