### ISSUE TITLE
New User Profile Design: use _auth as authentication object, update auth api

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/skygear-server#393]
https://github.com/SkygearIO/features/pull/68

- [ ] New database schema
  - [x] `_auth`
  - [x] `_user`, a view for backward compatibility
- [ ] Migrate database schema for skygear-server version upgrade
  - [x] Rename `_user` table to `_auth`
  - [x] Create a view named `_user` for backward compatibility
  - [x] Rename field `auth` to `provider_info` in `_auth`
  - [x] Move `username` and `email` from `_auth` to `user`
- [ ] Update signup and login api for the updated database schema and env. var.
  - [x] Migrate `user` table according to env. var. `AUTH_RECORD_KEYS` when signup
  - [x] new signup api signature: `signup(authData, password, profile?)`, where `authData` is defined in `AUTH_RECORD_FIELDS` and profile is a dictionary and is optional
  - [x] new login api signature: `login(authData, password)`

Note:
This issue is not taking care of field-base ACL.

## handling `AUTH_RECORD_TYPE` and `AUTH_RECORD_FIELDS` in `user` table migration

Default values:
- AUTH_RECORD_TYPE: `user`
- AUTH_RECORD_FIELDS: `username,email`

Note:
`Migration steps` below means the operations performed by skygear-sever when server version upgraded, and when `AUTH_RECORD_TYPE` and `AUTH_RECORD_FIELDS` may or may not be presented.

### scenario 1:

- AUTH_RECORD_TYPE NOT specified
- AUTH_RECORD_FIELDS NOT specified

Migration steps:
1. Move `username` and `email` from `_auth` to `user`
1. Add unique constraint to `username` to `user`
1. Add unique constraint to `email` to `user`

### scenario 2:

- AUTH_RECORD_TYPE set to `human`
- AUTH_RECORD_FIELDS NOT specified

Migration steps:
1. Move `username` and `email` from `_auth` to `user`
1. Add unique constraint to `username` to `user`
1. Add unique constraint to `email` to `user`
1. Rename table `user` to `human`

### scenario 3:

- AUTH_RECORD_TYPE NOT specified
- AUTH_RECORD_FIELDS set to `username,(username,email)`, meaning `username` is required and `email` is optional

Migration steps:
1. Move `username` and `email` from `_auth` to `user`
1. Add unique constraint to `username` to `user`
1. Add unique constraint to `username` and `email` to `user`

### scenario 4:

- AUTH_RECORD_TYPE NOT specified
- AUTH_RECORD_FIELDS set to `phone_number`
- `phone_number ` was not in `user`

Migration steps:
1. Move `username` and `email` from `_auth` to `user`
1. Add unique constraint to `phone_number ` to `user`
1. FAILED!

### scenario 5:

- AUTH_RECORD_TYPE NOT specified
- AUTH_RECORD_FIELDS set to `phone_number`
- `phone_number ` has been in `user` but not unique

Migration steps:
1. Move `username` and `email` from `_auth` to `user`
1. Add unique constraint to `phone_number ` to `user`
1. FAILED!

## old `_user` schema

- `id (text)`
- `username (text)`
- `email (text)`
- `password (text)`
- `auth (jsonb)`
- `token_valid_since`
- `last_login_at`
- `last_seen_at`

## new `_auth` schema

- `id (text)`: should be the same as `user._id` as a convention
- `password (text)`: the password for authentication
- `provider_info (jsonb)`: the authentication information from Authentication
  Provider
- `token_valid_since`: the timestamp limit the validity of the authentication
  token
- `last_login_at`: the timestamp when the user last login
- `last_seen_at`: the timestamp when user last perform an action

**Comment by Steven-Chan** [comment]
There are some problem when renaming `_user` to `_auth`, even adding view `_user`.

1. you cannot create a foreign key reference on a column of a view so if there is any column referencing the old _user.id would fail the migration
1. naming problem, I think the new names below are not as good as the older ones.
  1. `_user_role` would be renamed to `_auth_role`
  1. any column named `user_id` would be renamed to `auth_id`, we cannot force user to do this but at least the internal table columns would be renamed

**Comment by Steven-Chan** [comment]
Update:

- Remove `AUTH_RECORD_TYPE`
- Skygear db migration is not affected by `AUTH_RECORD_FIELDS` , so `username` and `email` are moved from `_auth` to `user` no matter what

**Comment by chpapa** [comment]
Remove `AUTH_RECORD_TYPE` will need to update the feature spec at SkygearIO/features#48

**Comment by Steven-Chan** [comment]
There is a problem not described in this issue, which is the current username and email in _auth is case insensitive, while under the current database schema implementation, citext is not recognized. After some offline discussion, we have come to a few conclusion:

- Auth columns in record table must be citext and unique.
- Skygear server will do the migration for the developer.
- This migration would be done when user sign up or login, and the server find that the db schema does not match with corresponding environment variable.
- When doing migration, if the new auth column has already been existed in the table, regarding the type of the column:
  - if the column is citext already, nothing would be done
  - if the column is text, it would be migrated to citext
  - otherwise, the migration would fail, as conflicting field type
  - if the column is a reference to another table, it would fail
- If a column was an auth column and not found in the new auth columns, the server would not migrate this column.
- If citext is presented as a field type in record table, it would be treated as normal text.
- The migration would NOT happen in Skygear upgrade database migration, so the default auth column username and email would be presented in the user table as citext and unique.

@cheungpat please see if the above description align with your expectation.

**Comment by cheungpat** [comment]
@Steven-Chan I am okay with that.

**Comment by rickmak** [comment]
I am okay to do text to citext conversation.

Don't do type conversation, since user won't expected the return type will be changed without his action.

**Comment by Steven-Chan** [comment]
After some offline discussion, I come up with this conclusion (sorry @cheungpat for changing my mind so quickly):

The principal is:

- Since the auth data are stored in user record, they are no longer fully system maintained data
- But auth data must be unique, while Skygear does not provide a way to make a record field unique, Skygear will try to maintain this for the developer

So:

- Auth data column type must be the following skydb types (I think this restriction is good enough to keep the maintainability while this cover most use case)
  - TypeString
  - TypeNumber
  - TypeInteger
  - TypeBoolean
  - TypeSequence
- Auth data column must have a unique constraint
- Skygear server will check schema and do migration aggressively in dev mode
  - If the a column was not unique, skygear will use a special name to create a unique constraint, and maintain it for the developer, just like underscore column type. Otherwise, skygear will not maintain the existing unique constraints.
- Skygear server will fail to start if schema does not match with setting in non dev mode

For the need of case insensitive comparison, Skygear may introduce case insensitive string and provide a way to make a record field case insensitive string. This seems to be needed, because after introducing field-based ACL and field discoverability, if one want to make a record field case insensitively discoverable, iLike cannot get this job done. I think this is not that urgent, because as long as Skygear can handle citext, it would still work even if the developer change a record column to citext in db directly.


### Scenario 1
```
DEV_MODE=1
AUTH_RECORD_KEYS=colA,colB,colC

- Server startup
  - if user schema does not have colA 
    - pass (because server does not enough information to do the migration)
  - if user schema has colB, but no unique
    - add unique constraint to colB with a special name
  - if user schema has colC with unique
    - pass
  - Remove all special unique constraint of columns that are not in AUTH_RECORD_KEYS in user

- Signup
  - if user schema does not have colA 
    - get auth data from signup payload
    - get data type of colA
    - create colA with unique constraint

- Save record
  - if record type is user
    - if record saved has colA
      - if user schema does not have colA 
        - get auth data from signup payload
        - get data type of colA
        - create colA with unique constraint

- Login
  - do nothing
```

### Scenario 2
```
DEV_MODE=0
AUTH_RECORD_KEYS=colA,colB,colC

- Server startup
  - if db schema does not match AUTH_RECORD_KEYS or the columns does not fulfill the requirement
    - fail
```

**Comment by cheungpat** [comment]
@rickmak The only implication I found with @Steven-Chan latest proposal is that:

Authentication of a user depends on the type of the auth column (set in `AUTH_RECORD_KEYS`). If the type of the column is `text`, the comparison will be case sensitive, if the type of the column is `citext`, the comparison will be case insensitive. Skygear Server will *NOT* migrate `text` to `citext` or vice versa.

The auth column will be created with `citext` type by default. The column type can be `text` if the column is created before the developer set `AUTH_RECORD_KEYS`.

I think the previous conclusion was that the column type `text` > `citext` conversion will be done by Skygear Server automatically. This proposal does not convert the type of the column.
