### ISSUE TITLE
Lambda cannot return an array

### ISSUE THREAD

**Issue by howawong** [SkygearIO/skygear-server#410]
When a lambda return array, then the following error is occurred.

### Sample Lambda
```python
def register_message_lambdas(settings):
        @skygear.op("chat:get_messages", auth_required=True, user_required=True)
            def get_messages_lambda(conversation_id, limit, before_time=None):
                return ["a", "b", "c"]
```

### Sample Response
```json
{
	"error": {
		"name": "UnexpectedError",
		"code": 10000,
		"message": "json: cannot unmarshal array into Go value of type map[string]interface {}"
	}
}
```

- Skygear Server Date/Version: 0.24.0

#### Expected Results
return an array out of plugin

#### Actual Results
500 Internal Server Error occurred

#### Steps to reproduce
1. Call the above sample lambda

**Comment by howawong** [comment]
Hi, any update on this? Is it a limitation in golang or what?

**Comment by cheungpat** [comment]
Probably need to change this line to an interface: https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/plugin/lambda.go#L91

**Comment by chpapa** [comment]
@howawong if you wish / think this should be scheduled in next house keeping milestones, maybe you can (discuss with the team) and bump the vote to 2 or 3?

**Comment by david90** [comment]
I've been asked serval times by users as well, so here's a upvote from me.

**Comment by chpapa** [comment]
> I've been asked serval times by users as well, so here's a upvote from me.

Let me just bump it to vote/3, if it have been asked **several times**

**Comment by howawong** [comment]
Actually, i did not think of priority when prompting. I just checked my created issues and found few of them hang somehow. I think @david90 or @carmenlau  can decide the priority.

**Comment by carmenlau** [comment]
To handle this, we also need to check all client SDK handled this appropriately

**Comment by cheungpat** [comment]
This issue will be covered by SkygearIO/features#100
