### ISSUE TITLE
new user is not assigned with the default role

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/skygear-server#44]
A new signup user should belong to the default user role.

- Skygear Server Date/Version: v0.12.0
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
The new user is assigned with default role 'user'

#### Actual Results
The new user is not assigned with any roles. The table `_user_role` is empty.

#### Steps to reproduce

1. set a default role, e.g. 'user', such that the `_role` table is like:
<img width="559" alt="screen shot 2016-06-02 at 11 03 58" src="https://cloud.githubusercontent.com/assets/246195/15732731/30e5b828-28b2-11e6-8e1b-51ff86f40a4d.png">

2. sign up a new user
3. the `_user_role` table is empty

##### Script to reproduce:

```
#!/bin/bash

export SKYGEAR_ENDPOINT=${SKYGEAR_ENDPOINT:=http://localhost:3000}
export SKYGEAR_APIKEY=${SKYGEAR_APIKEY:=apikey}

# create the first user, who will create a default role
USER1_SIGNUP_PAYLOAD='{"action": "auth:signup", "api_key": "'$SKYGEAR_APIKEY'", "username": "testuser1", "email": "testuser1@example.com", "password": "password"}'
SKYGEAR_ACCESS_TOKEN=`curl -X POST $SKYGEAR_ENDPOINT/auth/signup -d "$USER1_SIGNUP_PAYLOAD" | sed "s/.*access_token\": *\"\([^\"]*\)\".*/\1/"`

export SKYGEAR_ACCESS_TOKEN

# create default role 'user', in table `_role` with {'by_default': true}
DEFAULT_ROLE_PAYLOAD='{"action": "role:default", "api_key": "'$SKYGEAR_APIKEY'", "access_token": "'$SKYGEAR_ACCESS_TOKEN'", "roles": ["user"]}'
curl -XPOST $SKYGEAR_ENDPOINT/role/default -d "$DEFAULT_ROLE_PAYLOAD"

# sign up another user, but no records found in table `_user_role`
USER2_SIGNUP_PAYLOAD='{"action": "auth:signup", "api_key": "'$SKYGEAR_APIKEY'", "username": "testuser2", "email": "testuser2@example.com", "password": "password"}'
curl -X POST $SKYGEAR_ENDPOINT/auth/signup -d "$USER2_SIGNUP_PAYLOAD"
```

**Comment by TakLee96** [comment]
I also noticed that even roles are defined and saved on a user, whenever your retrieve the user through `skygear.getUsersByEmail` or by logging in and get `skygear.currentUser`, the `user.roles` is always an empty array.
