### ISSUE TITLE
Looping on sending push notification may result in some push notification missing

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-server#47]
Case 1:
Put a for loop to send push notification in cloud code. Some push notification may be missed.

Case 2:
If a user has a lot of device tokens, some of them may be missed when we send push notification to that user

**Comment by cheungpat** [comment]
I still think switching to the new HTTP/2 protocol/library is the way to go. At least you get response from APNS.

I think this might be relevant to the problem you are seeing
https://github.com/timehop/apns/issues/70
