### ISSUE TITLE
Add all environment variable to .env

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-server#471]
Current, there are a lot of environment variable not mentioned anywhere. I think we should just keep .env.example updated with the environment variables so advanced users can reference it.

Should be in this file:
https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/skyconfig/config.go

**Comment by simonstaton** [comment]
Going to jump on this now for hacktober

**Comment by blockloop** [comment]
You just want a `.env.example` file in the root with all environment variables referenced in `config.go`?

**Comment by blockloop** [comment]
I'll take this one. Just need a little more info.

**Comment by chpapa** [comment]
Cool @blockloop , basic is list out, but better have a short one line description. If you need help try to ask here?

**Comment by blockloop** [comment]
K got the list now. Working on reading the code and leaving as many comments as I can parse out now.

**Comment by blockloop** [comment]
Okay let me know if that's sufficient.

**Comment by rickmak** [comment]
I added some update and merge the PR. Please comments and see if is sufficient.
