### ISSUE TITLE
[Bug] Skygear auth api (role:get) InvalidArgument

### ISSUE THREAD

**Issue by samMeow** [SkygearIO/skygear-server#475]
Ref: https://github.com/SkygearIO/skygear-SDK-JS/blob/3e942228bc7fae2d71768c65c273dcb01eebd94f/packages/skygear-core/lib/auth.js#L289

Ref: https://github.com/SkygearIO/skygear-SDK-Android/blob/e07a9d30b983299ba56315efa88c121bb27d3aa2/skygear/src/main/java/io/skygear/skygear/FetchUserRoleRequest.java#L17

Server Ref: https://github.com/SkygearIO/skygear-server/blob/1374e53d1b8ff359a7be50aded60aeec4723e85a/pkg/server/handler/role.go#L312

The client SDK pass `user` arguments for `skygear.auth.fetchUserRole` while server expected as `user_ids`
Should update skygear-server to receive `user` as arguments for consistency of roles api.

**Comment by cheungpat** [comment]
I would like to take over this bug.
