### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by Rajan** [SkygearIO/skygear-server#52]
Does skygear-server support MQTT protocol or something similar which consumes less battery on a mobile device?

**Comment by chpapa** [comment]
@Rajan MQTT support is on our roadmap but our intended design is for some data synchronisation usage on IoT application.

May I learn more about why are you interested in this and what are use cases so maybe we can adjust the roadmap / requirements?

**Comment by Rajan** [comment]
Building mobile chat requires a good low-energy mechanism to send/receive messages. MQTT happens to be that. Even Fb messenger and whatsapp use MQTT as a transport. So, I was assuming that your server/chat development kit would have it as a default!

**Comment by chpapa** [comment]
@Rajan interesting. that's something we could consider. However HTTP2 is catching up with its reasonably small footprint, support of persistent connection and more extensible. Some interesting discussion here too: http://timkellogg.me/blog/2015/02/20/can-http2-replace-mqtt

Our core team will look into it and if you're interested to contribute we would be happy to help discuss what are the possible architecture to support more transport protocol on the server.

**Comment by chpapa** [comment]
Moved to skygeario/features#15
