### ISSUE TITLE
[Audit, Password] Fine grained audit errors

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#528]
I just realised that audit errors are too fine grained.

```
	// PasswordTooShort is returned when the password is too short.
	PasswordTooShort

	// PasswordUppercaseRequired is returned when the password
	// does not contain ASCII uppercase character
	PasswordUppercaseRequired

	// PasswordLowercaseRequired is returned when the password
	// does not contain ASCII lowercase character
	PasswordLowercaseRequired

	// PasswordDigitRequired is returned when the password
	// does not contain ASCII digit character
	PasswordDigitRequired

	// PasswordSymbolRequired is returned when the password
	// does not contain ASCII non-alphanumeric character
	PasswordSymbolRequired

	// PasswordBelowGuessableLevel is returned when the password
	// guessable level is below configured level
	PasswordBelowGuessableLevel

	// PasswordContainingExcludedKeywords is returned when the password
	// contains configured excluded keywords
	PasswordContainingExcludedKeywords

	// PasswordReused is returned when the password
	// is the same as a historical password.
	PasswordReused

	// PasswordExpired is returned when the password
	// is expired
	PasswordExpired
```

For each of these error codes

* the developer need to check all of these error codes so that they know the password is rejected for policy reasons, if the developer is only interested whether the password is rejected due to policy reasons, they have to check all of these codes.

* each SDK need a error message describing each of these rejection scenarios

The agreed way to handle this is to add a `PolicyRejected` and include the failure reason in the error info dictionary.

**Comment by cheungpat** [comment]
@louischan-oursky @rickmak

**Comment by rickmak** [comment]
At first, I think the SDK can do a range check on the Error code. But seem it will imply the SDK error handling is difficult to use.

Seem the PolicyRejected is enough for most case...

**Comment by louischan-oursky** [comment]
I admit that it is a bit too fine grained but as Rick said, we can always perform a range check to see if the error is PolicyRejected.

Another reason I made the error so verbose is that I want to be localization friendly.

For example, PasswordTooShort error will include [two keys in the info dictionary](https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/audit/password_checker_test.go#L153) to aid developer to localize the error message

@cheungpat @rickmak

**Comment by louischan-oursky** [comment]
Or we can use only one code and add `type` to the info dictionary to allow developer to differentiate different kinds of errors. I did not do this because it seems no existing error does this.

**Comment by chpapa** [comment]
Actually I like the idea of range check, but once we decided we need to make sure other APIs aligned too?

**Comment by rickmak** [comment]
Side note of PR#544,

@louischan-oursky and @cheungpat have an offline discussion on categorizing the error into multiple levels.

The current consensus is the fine gain errors will be in the `info` key path. This will make the error handling more specific to the domain, and avoid a premature design of universal error interface.
