### ISSUE TITLE
container.signup* function should have an optional parameter to create user profile

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/skygear-server#54]
We are talking about:

signupAnonymously
signupWithEmail,
singupWithUsername, and
default behaviour for skygear.providers.BaseAuthProvider here.

We should have an optional parameter such as "savePublicUserProfile", default is true and when set to true, we will copy the username, email, and everything else to the User table. (Consider change the name of User table to UserProfile?)

The intention is to provide a default which is easier for new developers of Skygear

**Comment by TakLee96** [comment]
It seems that currently after `skygear.signupWithEmail`, the user is visible publicly (by calling `skygear.getUsersByEmail`)

**Comment by rickmak** [comment]
`skygear.getUsersByEmail` is intended for admin use, please see 7f5f5c9 for update. Only user belongs to admin role is able to query the user by email. For other user, they should query the `user` record using record query.

**Comment by rickmak** [comment]
In various discussion, see following API is better than just a boolean parameter on creating a UserRecord.

We will implement with the third parameter as complete initial user attributes. Following is a js example.

``` js
skygear. singupWithUsername(username, password, {
  "email": "saveme@skygear.io",
  "firstname": "Save",
  "lastname": "Me"
}).then((user) => {
  console.log(user.firstname); // Save
  console.log('access token: %s', skygear.currentAccessToken);
}, (error) => {
  console.log('error signing up: %o', error);
});
```

**Comment by louischan-oursky** [comment]
it would be great if the third parameter also accept `_recordType` which gives the ability to override the target table.

**Comment by rickmak** [comment]
@louischan-oursky Under what use case this option will be useful? Why the `user` table don't works for you?

**Comment by louischan-oursky** [comment]
@rickmak One possible use-case I can think of is that the kinds of user are differentiated by table, not by an enum column in `user` table

```
const aid = uuid.v4();
skygear.signupAnonymously({
  '_id': `anonymous_user/${aid}`,
});

const uid = uuid.v4();
skygear.signupWithUsername(username, password, {
  '_id': `user/${uid}`,
  'firstname': 'Louis',
  'lastname': 'Chan',
});
```

**Comment by b123400** [comment]
Sorry I have not join any conversation about User Profile, by reading the issues and comments I assume it is about "Users are saved in `_user`, which is not extendable (e.g. add a new column)"?

And the current discussion is about whether we should:
1. Make `_user` table extendable, or
2. Make it possible to save users in a record-based table, so they are extendable?

If I am understanding it correctly, (2) seems to be a more generic solution, for example we can implement user query on top of record query.

**Comment by rickmak** [comment]
Yes, you can reference here: https://docs.skygear.io/guides/auth/user-profile/js/

So the short answer is 2. We created a `user` record on every user signup <sup>[code]</sup>, they have the same ID. So we can use all record query the on `user` record. The scope of this issue is to make the signup and user attributes setting 1 SDK call. 

Let make js as example:

This works, but not nice.

```
skygear. singupWithUsername(username, password).then((user) => {
  const profile  = new skygear.UserRecord({
    "email": "saveme@skygear.io",
    "firstname": "Save",
    "lastname": "Me"
  });
  return skygear.publicDB.save(profile).then((profile) => {
    console.log(profile); // updated user record
  });
}, (error) => {
  console.log('error signing up: %o', error);
});
```

```
skygear. singupWithUsername(username, password, {
  "email": "saveme@skygear.io",
  "firstname": "Save",
  "lastname": "Me"
}).then((user) => {
  console.log(user.firstname); // Saved UserRecord
  console.log('access token: %s', skygear.currentAccessToken);
}, (error) => {
  console.log('error signing up: %o', error);
});
```

[code]: https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/handler/auth.go#L516

**Comment by chpapa** [comment]
@rickmak @b123400 this reminds me of the discussion of "best practices to store user profile" and it involve ACL. Shall we design the user profile sdk API so that it "teach" or "help" users to handle common cases like:

- user profile attribute which is public and listable (public info)
- user profile attribute which is public but not listable  (E.g. email address or or user URL slug)
- user profile attribute which is private
- (is there any case for private but listable?)
- custom ACL

This might make the signature more complicated, but there is a chance we can improve usability a lot here!

**Comment by chpapa** [comment]
The API and Guides need to cover the following:
* Public / Private User Profile Creation
* Custom User Profile Creation (e.g. Role based - Friends Profile), initial discussion is include in Guide only
* Discoverable User Profile Attribute (e.g. User Slug), include in Guide only

**Comment by b123400** [comment]
I actually think your "not nice" code is ok, you are just not utilising Promise, but the idea should be the same.

```
skygear.singupWithUsername(username, password)
  .then(userToProfile) // this is the function user needs to implement
  .then(skygear.PublicDB.save)
  .then(console.log) // succeeded
  .catch(console.warn) // failed
```

User can easily extend it to support multiple profiles, just change it to something like this:

```
skygear.singupWithUsername(username, password)
  .then(u=> [userToPublicProfile(u), userToPrivateProfile(u)])
  .then(profiles => profiles.map(skygear.PublicDB.save))
  .then(Promise.all)
  .then(console.log) // succeeded
  .catch(console.warn) // failed
```

I think the above design is good enough, and multiple function calls is actually better because we are actually creating multiple records, but if single function call is preferred, maybe we can do this:

```
const userToPublicProfile = user => new PublicProfile({ "name": ... });
const userToPrivateProfile = user => new PublicProfile({ "secret": ... });

skygear.singupWithUsername(username, password, {
  "publicProfile": userToPublicProfile,
  "privateProfile": userToPrivateProfile
})
  .then(user => {
    // which is better?
    // user.publicProfile
    // user.$transient.publicProfile
  }) // succeeded
  .catch(console.warn) // failed
```

**Comment by chpapa** [comment]
I can't really judge here.... and also need to see how would it works for iOS and Android?

Can someone else comment too? @ben181231 @louischan-oursky 

@b123400 maybe you want to post on Slack for more comments from others? :)

**Comment by ben181231** [comment]
@b123400 I like the functional style and it is more like what we have now. But I think some developers may want the single function version since it wraps the logic between the user object (i.e. `_user` table) and the user record.

Or, giving a detailed documentation can solve this?

**Comment by b123400** [comment]
Oh yes `userToProfile` has to include connecting user to profile...
How about accepting an optional function of `user -> [profile]`? Will it be confusing?

```
signup(username, password, user=> [userToProfile(user)])
  .then(console.log)
```

Signup will "bind" them together after receiving the profile.

-----

> also need to see how would it works for iOS and Android?

Do we have to design an API that works across JS, iOS, Android, 3 platforms 3 languages?
That would make it pretty difficult to utilise language feature, like on iOS I don't think we are using promise

**Comment by chpapa** [comment]
@b123400 It is better to have similar functions across different platform. But I think we should use the best (or most common) language feature of each platform to provide similar functions.

**Comment by rickmak** [comment]
First, this issue can be not purely SDK only. We have the option to change the signup API to accept the profile data in one API call.

Second, **not nice** is the feedback I got from various developers. They think it should be one API call, they don't want to understand there is two things at the very beginning.

### platform

Yes, we need to design for all JS, iOS and Android.

`best` or `most common` language feature !== entry level friendly.

You can utilise language features, but keep in mind our target user is not language expert. Using all language feature to make it looks nice is not our target. We should try to confront the language common/best practices and the way of doing things, which of course involve using of language features.

### Target user

```
skygear.singupWithUsername(username, password)
  .then(userToProfile) // this is the function users need to implement
  .then(skygear.PublicDB.save)
  .then(console.log) // succeeded
  .catch(console.warn) // failed
```

I think this code snippet will not be understand by 80% of fresh graduate. Of coz we can tech them by documentation.


### Option

0. Teach user by example, words, demo, documentation and keep current API signature.
1. Keep it SDK wise 1 API call
2. Make it real 1 API call by modifying the `auth:signup`, which I think @b123400 will feel better?

0 is what we tried, may be we are not working hard enough. We can still try and prove it work (or not)

To user, 1 or 2 make no different at first. They will notice latency different in a long run. My believe is 1 API call will be easier to onboard.

**Comment by b123400** [comment]
OK, I will follow your choice of (1). Since people don't understand function, how about API like this:

```
skygear.signupWithUsernameAndProfile(username, password, {
  'PublicProfile': {
    'firstname': 'hi'
  }
})
```

Which would do something like this internally:

```
let PublicProfile = new skygear.Record.extend('PublicProfile')
let profile = new PublicProfile({
  'firstname': 'hi',
  'user': user,      // automatically associate the new user
})
publicDB.save(profile)
```

Actually you have much better understanding on our target user, maybe you can give some advise on how the API should be like? I have no idea what is considered to be nice by them

**Comment by chpapa** [comment]
I think in this case, it is not really relevant to "bad" understanding of target user?

It is just about try to design the SDK method signature in a way that is self-documentary and easy to understand?

Compare with the 2nd approach, I think the problem of 1st approach is users need to understand lots more:

1. They need to understand how Promise works (which is a good assumption, I think for now we can consider Promise is a popular enough feature amongst JS developers)
2. They need to know they should make a User Record themselves (Which is a skygear specific things, people can't guess from the API reference or method signature)

1 is good, 2 is bad.

The new code snippet method signature and sample code make it more trivial on what's happening. (Is there any better approach?)

**Comment by rickmak** [comment]
@b123400 Please try to understand that we already have a `user` record created by `skygear-server`. So the `PublicProfile` will create noise. Just a dict that only able to update the gifted `user` record will be fine.

**Comment by b123400** [comment]
Ok, so we will not be supporting custom recordType for user profile

**Comment by chpapa** [comment]
Hmmm, refer to @louischan-oursky comment above, maybe it is actually a good idea that we allow multiple profile / profile with custom record name?

I think if we include the User Profile name in the method signature / sample code, it would also help developers to understand what it does.

**Comment by b123400** [comment]
How about this, 2 APIs:

```
singupWithUsername(username, password, {
  name: "some name" // this will be put into the `user` table
})
```

If multiple profiles are needed: 

```
singupWithUsernameAndProfiles(username, password, {
  "user": {
    name: "some name"
  },
  "private_user": {
    secret: ...
  }
})
```

**Comment by rickmak** [comment]
Any iOS and Android SDK issue follow up this issue?
