### ISSUE TITLE
Async hooks are not called in HTTP transport

### ISSUE THREAD

**Issue by yipsang** [SkygearIO/skygear-server#553]
- Skygear Server Date/Version: 1.3.3

#### Steps to reproduce

1. Signup a user with sso (user after_save hook is called)
2. Update user record (user after_save hook is not called)

The hook is defined in this way:
```
@skygear.after_save('user', async=True)
@with_session
def after_save_user(session, record, original_record, db):
    _send_verification_email_if_needed(session, record)
    return record
```

**Comment by carmenlau** [comment]
@yipsang Tried locally and cannot reproduce the problem. In my testing I removed your `with_session ` decoration. Would like to see

1. Can you try remove `with_session` and see if it will be called?
2. Do you have this problem in your dev environment? If so, in the skygear server log can you see user's `afterSave` registered?

thanks >"<

**Comment by carmenlau** [comment]
Verified it happens in http transport

**Comment by limouren** [comment]
zeromq is da best!

**Comment by cheungpat** [comment]
@limouren the same happens in ZMQ transport

**Comment by cheungpat** [comment]
@yipsang It would be great if you could try it out : ) you can fetch this image by pulling `quay.io/skygeario/skygear-server:canary`.

**Comment by yipsang** [comment]
@cheungpat cool! will try later
