### ISSUE TITLE
Need to update Facebook Login permissions as some of them are deprecated

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/skygear-server#600]
Facebook has recently deprecated quite a long list of Facebook login permissions, and we need to update them accordingly.

4/4/2018 blogpost (scroll to Facebook login): https://developers.facebook.com/blog/post/2018/04/04/facebook-api-platform-product-changes

24/4/2018 blogpost (scroll to Facebook login): https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates

- Skygear Server Date/Version:
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Steps to reproduce

1.
2.
3.

**Comment by chpapa** [comment]
Seems important? Does it affect normal usage? @tensiuyan @carmenlau

**Comment by carmenlau** [comment]
Will check and moved the issues to portal https://github.com/oursky/skygear-portal/issues/616
