### ISSUE TITLE
Support byte-range for serving video

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#616]
Mobile Safari requires http server to support byte-range in order to play video.

https://stackoverflow.com/questions/3397241/does-iphone-ipad-safari-require-accept-ranges-header-for-video

The current skygear server with fs asset store doesn’t support this header, therefore cannot support the use case to play uploaded video to be played in browser.

- Skygear Server Date/Version: 1.6.1
- Application Platform: web
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

**Comment by ben181231** [comment]
Is it duplicated with #387 ?

**Comment by carmenlau** [comment]
Merged to master via 7ac6006, and we need a patch for v1-branch.
