### ISSUE TITLE
add chat plugins to skygear server on localhost

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/skygear-server#618]
Hi 
i work for run skygear sever on my localhost 
skygear server is run on localhost using last skygear release (binary file)
and i'm trying to add chat plugin 
how to (Run skygear-node in your project folder. Skygear will look for index.js as entry point and run your code) if i used binary file how to do that ??

**Comment by chpapa** [comment]
@KhaledAld May you post your question on the discussion forum? https://discuss.skygear.io/ Thanks!
