### ISSUE TITLE
Enable push  notification in local

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/skygear-server#641]
Hi 
i'm working on run skysearver as virtual box from docker-compose.yml file.
how to enable push notifications  , and where is the path of APNS Certificate (.pem file) ?

**Comment by tensiuyan** [comment]
@KhaledAld please refer to this discussion thread: https://discuss.skygear.io/t/example-for-skygear-environment-variables/157/2

closing this issue since this is not a bug report.
