### ISSUE TITLE
skygear server is working slow on local deployment

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/skygear-server#676]
Hi There,

I'm using skygear on my local server and everything works fine.
but Socket is dorp every to second (for example) and chat is working too slowly

any suggestion ??

Thanks

**Comment by tensiuyan** [comment]
Hello @KhaledAld for support please reach us over [Skygear forum](https://discuss.skygear.io) or [Slack](https://slack.skygear.io).

Closing this issue as this is not a bug report.
