### ISSUE TITLE
Transaction management in next

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#682]
The party involve are:

- HandlerFactory
- DependencyMap
- Handler

There is handler that require fine control on transcation depending on the actual payload. The transaction is management is application logic. We need to provide a way for handler to control over the transaction.

**Comment by chpapa** [comment]
@Steven-Chan If it is only becoz Record API need to have multiple transactions in a single request and complicate everything, my gut feeling is that's a good tradeoff to keep thing simple but only support atomic request in record API... (just 2 cents)

**Comment by Steven-Chan** [comment]
> If it is only becoz Record API need to have multiple transactions in a single request and complicate everything

Yes, but not entirely. I am not sure if the record save API is the only one (now or future) which require fine control on db transaction.

If we go for proposal 2, that will straightly shut down such ability. I don't think such sacrifice is actually worth, unless we find a way to allow handler to have ability to fine control, or we have a philosophy on skygear API design that each request must be atomic on db operation.

**Comment by Steven-Chan** [comment]
Did some searching on current skygear-server code base.

At handler level:
- create auth db data and create user record in `authutil.go`
- `atomicModifyFunc` in record save handler

At preprocessor level:
- create user in preprocessor

At skydb/pq level:
- `SetRecordFieldAccess`
- migration
- schema `Extend`

---

Notes:

- Transaction management at `skydb/pq` level would be removed.
- Preprocessor is removed already
- We have not yet provided the exact same replacement of `create user in preprocessor` in next yet
- create auth and create user record in `authutil.go`
  - we have decided not to keep one transaction for this

--- 

TODO: check existing plugin apis
