### ISSUE TITLE
Modify the dev_only preprocessors to allow overwrite by master-key

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#76]
__Rationale__
we are using `dev_only` preprocessors at two handler now: `role` and `schema`. Which is very handy to modify role/schema as wishes during development. But in actual usecase, we also need to do role/schema related operation on production deployment where `dev-mode` will be off. Currently, we will need to do that at DB level, or turn on `dev-mode` for a moment. Both way is not desired to make the deployment similar to development.

A better solution will be the preprocessors will allow pass through by following condition:
`dev-mode` is true or`master-key` is correct

- Skygear Server Date/Version: v0.13

**Comment by cheungpat** [comment]
`DevOnlyPreprocessor` currently behaves like you described.
