### ISSUE TITLE
next: Fix signup auth record keys checking

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/skygear-server#795]
Current impl:

- There is a unique constraint on `_auth_provider_password.auth_data`.
- Default auth record keys setting is `username,email`.

Behaviour:

1. Signup with `{"username": "user1", "email": "user1@oursky.com"}` -> success
1. Signup with `{"username": "user2", "email": "user1@oursky.com"}` -> in v1, this should fail, but now success

According to the original design of auth record keys, each key or key combination (e.g. `a,b,(c,d,e)`) should be unique in the table.

We need to update auth data handling to match the correct auth record keys behaviour.

~~Since we don't have JIT db migration now, we can't change constraint when settings get update. We have a few approaches:~~
- ~~When signup, check unique constraint matched auth record keys setting~~
- ~~When signup, query with provided auth data, and check if there is a user existed already~~
- ~~When login, query with provided auth data, and check if more than one user found~~

**Comment by Steven-Chan** [comment]
I've come up with a more sensible solution, which does not require setting constraints based on the auth record keys setting.

The auth data json should respect the auth record keys setting. E.g. the default setting `username,email`, it means user should either use username or email to login.

If, for the simplest case, a user signup with username only, there should be one signup entry:

- `auth_data`: `{username: xxxx}` + `password`: `xxxx`

If a user signup with **both** username and email, there should be two signup entries:

- `auth_data`: `{username: xxxx}` + `password`: `xxxx`
- `auth_data`: `{email: xxxx}` + `password`: `xxxx`

In next, there should be two entries of principal.

If the auth record keys settings is like `username,(email,nickname)` and a user signup with data with all three fields, the backend should save:

- `auth_data`: `{username: xxxx}` + `password`: `xxxx`
- `auth_data`: `{email: xxxx, nickname: xxxx}` + `password`: `xxxx`

This above changes implies that:

- we need to remove the constraint that each user can only have one principal of one provider
- when changing password for one user, all the password principals for that user need to be updated 
- any underlying function that needs to get principals of one user, it must return an array of principal instead of a single principal

**Comment by tensiuyan** [comment]
https://github.com/SkygearIO/features/blob/master/features/48-user-profile-discovery/user-profile.md#authentication-record-configurations

**Comment by Steven-Chan** [comment]
Try translating the config to a logic may help understand the behaviour.

## Case 1
`keys = [["username", "email"], ["username", "phone"]]` => accept when (`username` AND `email`) OR (`username` AND `phone`)

```
authData ={
  "username": "johndoe",
  "email": "johndoe@example.com"
} 
```

It fulfils (`username` AND `email`), thus it is valid.

## Case 2
`keys = [["username", "email"], ["nickname"]]` => accept when (`username` AND `email`) OR (`nickname`)

```
authData ={
  "username": "johndoe",
  "nickname": "johndoe"
} 
```

It fulfils `nickname`, thus it is valid.

(The following is neither included in feature spec or v1) 

However, since the given auth data does not fulfil (`username` AND `email`) but (`nickname`) only. There would only one principal created with `nickname` in auth data.

So the user can only login with `nickname: johndoe`.

**Comment by Steven-Chan** [comment]
Please see if what i mentioned in the previous comment is correct @carmenlau @rickmak .

**Comment by carmenlau** [comment]
Yes, that's correct

**Comment by Steven-Chan** [comment]
@kaojohnny note that there is a statement in the feature spec `the list of unique constraints on the corresponding table of the authentication record.`, it is related to v1 implementation, so it may not be true in next.

**Comment by kaojohnny** [comment]
@carmenlau @Steven-Chan Thanks.

**Comment by rickmak** [comment]
> https://github.com/SkygearIO/skygear-server/issues/795#issuecomment-440972083

Is align with my understanding.
