### ISSUE TITLE
Cannot required skygear in node

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#80]
`require('skygear');` will result error.

- Skygear Server Date/Version: v0.13
- Application Platform:
- [x] Is this a regression?

#### Expected Results
It works with in process memory storage

#### Actual Results

Error: Cannot find module 'localStorage'`

#### Steps to reproduce

1. npm install skygear
1. node
1. require('skygear');

**Comment by cheungpat** [comment]
moved to SkygearIO/skygear-SDK-JS#35
