### ISSUE TITLE
Support some new loginID related APIs

### ISSUE THREAD

**Issue by kaojohnny** [SkygearIO/skygear-server#923]
Require #917 

skygear next should support the following new APIs:

- [ ] login(loginIDValue: String, password: String)
- [ ] createLoginID(loginIDKey: String, loginIDValue: String)
- [ ] updateLoginID(loginIDKey: String, loginIDValue: String)
- [ ] removeLoginID(loginIDKey)

**Comment by chpapa** [comment]
Will we have the corresponding API for admin to change other users' login ID for Server Side codes? (I suppose these APIs are meant to be called from client side for current logged in user)

**Comment by louischan-oursky** [comment]
superseded by https://github.com/SkygearIO/skygear-server/issues/974
