### ISSUE TITLE
Add LoginID-Key information in the auth response

### ISSUE THREAD

**Issue by kaojohnny** [SkygearIO/skygear-server#924]
Require #917

skygear next should contain `LoginID-Key` information in the auth response. Such information can be placed in the HTTP response header.

```
LoginID-Key: username,
{
    user_id: <id>,
    login_ids: {
      role: 'admin',
      phone: '12345',
      username: 'example',
      email: 'example@example.com'
    },
    metadata: {
      age: 18
    }
}
```

**Comment by chpapa** [comment]
> {
>     user_id: <id>,
>     login_ids: {
>       role: 'admin',
>       phone: '12345',
>       username: 'example',
>       email: 'example@example.com'
>     },
>     metadata: {
>       age: 18
>     }
> }

I think these are redundant?

**Comment by louischan-oursky** [comment]
This issue is no longer relevant. [This PR](https://github.com/SkygearIO/skygear-server/pull/963) implemented [the new design](https://github.com/SkygearIO/features/blob/master/features/329-identity-apis/api.md#sdk-api).
