### ISSUE TITLE
Update gateway to provide CORS header for CF

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-server#932]
Gateway should get the CORS setting from tenant config and update the headers. OPTIONS request should be handled by gateway, and should not route to the cloud code backend.

**Comment by tensiuyan** [comment]
ref #890

**Comment by louischan-oursky** [comment]
Use this library https://github.com/iawaknahc/originmatcher @kiootic

**Comment by louischan-oursky** [comment]
Done in https://github.com/SkygearIO/skygear-server/pull/941
